Nginx x accel simulation project
smartcoop/smart-cfa pull request #103
Opened 2022-05-02 14:21 UTC by Victor-van-Duijnen

[The PR relates to recreating the setup of nginx x-accel and includes:](https://smartjira.atlassian.net/browse/CFA-235)

-  The creation of a proxy (in docker config files) and a fake account app to redirect from.
-  Some tweaks in the authorization/authentication handlers for the proper redirection of unauthorized calls.

2022-05-02 14:43 UTC, LievenPraet requested changes

2022-05-02 14:43 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/AccountUser.cs
> +    public static List<SelectListItem> List => new()
Better to indicate that this prop returns list items and not entities
```suggestion
    public static List<SelectListItem> SelectListItems => new()
```

2022-05-02 14:43 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/Pages/Error.cshtml
> +<h2 class="text-danger">An error occurred while processing your request.</h2>
No points in headers
```suggestion
<h1 class="text-danger">Error</h1>
<h2 class="text-danger">An error occurred while processing your request</h2>
```

2022-05-02 14:43 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/Pages/cfa.cshtml.cs
> +    // }
Remove commented code

2022-05-02 14:44 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/Pages/Error.cshtml
> +<h2 class="text-danger">An error occurred while processing your request.</h2>
It's the default page that get generated when making a new project.

2022-05-02 15:07 UTC, maxime-poulain requested changes

2022-05-02 15:07 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
> +builder.Configuration.AddJsonFile("appsettings.Docker.json", optional: true, reloadOnChange: true);
I wonder if it is a good idea to add on top of a the Local.json another config.
If one prefer using docker for minio but wants to keep a local sql instance he should configure that in his Local.json file.

2022-05-02 15:53 UTC, maxime-poulain commented
I can't put it in the code review but
https://github.com/smartcoop/smart-cfa/blob/517b838935ab5a4a6e5cee5d7f5772ec34ef4bd3/src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/Requirements/AtLeastOneValidUserChartRevisionApprovalRequirement.cs#L42

you could also in the same time moves the if IsStaging befoe executing the query. No point to execute the query if we are already in staging.

2022-05-02 15:55 UTC, maxime-poulain requested changes

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/AccountUser.cs
> +    public static List<SelectListItem> List => new()
Hm this could have just been in the IndexPageModel but either way, fine for me.

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/Program.cs
> +    var app = builder.Build();
```suggestion
var app = builder.Build();
```
and BL

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/ProxyHeaderMiddleware.cs
> +        var request = context.Request.GetEncodedUrl();
can be removed.

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.AccountSimulation/ProxyRedirect.cs
> +        context.Response.Headers.Add("user_id", userId);
Well this one is  just a low suggestion but those header could be moved onto the shared project under a constant class

i assume those will be used in the user admin project right ?

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +{
file socped

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +    public class CustomAuthenticationHandler : AuthenticationHandler<CfaAuthenticationOptions>
Should just the authentication handler checks if the user-id is defined inside the header ?
In our case if the user is authenticated this means he got forwarded with a header.
there's no way to make this called before the middle ware that sets up things ?

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +            if (_userIdentity?.CurrentTrainer is null)
```suggestion
            if (_userIdentity.CurrentTrainer is null)
```

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +                return Task.FromResult(AuthenticateResult.Fail("Model is Empty"));
```suggestion
                return Task.FromResult(AuthenticateResult.Fail("There's no trainer associated to the current identity"));
```

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/List.cs
> +﻿namespace Smart.FA.Catalog.Web.Policies;
```suggestion
namespace Smart.FA.Catalog.Web.Authorization.Policies;
```

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/List.cs
>  public static class List
Usually when a class hold constants it uses plural.
You could say Names.

but I think the best things to do is name the folder Policy and name that class Policies.

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/UserAdminAuthorizationResultHandler.cs
> +namespace Smart.FA.Catalog.Web.Policies;
name space is incorrect

2022-05-02 15:55 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/UserAdminAuthorizationResultHandler.cs
> +    private readonly AuthorizationMiddlewareResultHandler defaultHandler = new();
```suggestion
    private readonly AuthorizationMiddlewareResultHandler _defaultHandler = new();
```

2022-05-03 07:06 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +        public CustomAuthenticationHandler(
Agreed for the "Custom" part, not sure "Catalog" would do it either, though. If we could I would like a way to differentiate it from a potential custom authentication handler in showcase (or any other projects that end up in the solution).
_"UserAdminAuthenticationHandler"_ simply, @LievenPraet @maxime-poulain ?

2022-05-03 07:09 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
> +builder.Configuration.AddJsonFile("appsettings.Docker.json", optional: true, reloadOnChange: true);
The thing is, I tend to switch constantly between one and the other. I debug with IIS but before pushing a branch to remote, I first run the docker compose, Maybe that's not the best right now but I am looking for a good way to do that.

2022-05-03 07:23 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/AuthSchemeConstants.cs
> +public static class AuthSchemeConstants
Hmm instinctively I agree with you but in 99% of the code I have seen, there is a postfix "Constants" for the class hosting the constants...

2022-05-03 07:26 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/List.cs
>  public static class List
Maybe Types would work? => Policy.Types.AtLeastOneValidUserChartRevisionApproval

2022-05-05 09:23 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +        public CustomAuthenticationHandler(
`CfaAuthenticationHandler`?

2022-05-05 09:27 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policies/List.cs
>  public static class List
Agreed. I like `Types`.

2022-05-05 10:06 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +        public CustomAuthenticationHandler(
Yes why not CfaUserAdminAuthenticationHandler. I would rather go with your second suggestion since Showcase (which is part of cfa, too) could use its own authentication handler in the futur maybe (though I don't see the point for what is planned right now).

2022-05-05 18:09 UTC, maxime-poulain requested changes

2022-05-05 18:09 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +        var userId = (string.IsNullOrEmpty(context.Request.Headers["userid"].ToString()) ? "1" : context.Request.Headers["userid"].ToString())!;
```suggestion
        var userId = string.IsNullOrEmpty(context.Request.Headers["userid"].ToString()) ? "1" : context.Request.Headers["userid"].ToString();
```

2022-05-05 18:09 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Handlers/UserAdminAuthorizationResultHandler.cs
> +        // Fall back to the default implementation.
```suggestion

        // Fall back to the default implementation.
```

2022-05-05 18:09 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/AtLeastOneValidUserChartRevisionApprovalRequirement.cs
> +            // If we are in staging we don't need to check for any approval of user charts
```suggestion
```

2022-05-05 18:09 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/AtLeastOneValidUserChartRevisionApprovalRequirement.cs
> +        if (!_webHostEnvironment.IsStaging())
```suggestion
         // If we are in staging we don't need to check for any approval of user charts
        if (!_webHostEnvironment.IsStaging())
```

2022-05-05 18:09 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Smart.FA.Catalog.Web.csproj
> -    <Content Update="appsettings.PreProduction.json">
Could you restore the csproj file formatting like it was please ?

2022-05-05 18:13 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/UserAdminAuthenticationHandler.cs
> +        public CustomAuthenticationHandler(
FAUserAdminAuthenticationHandler or FaUserAdminAuthenticationHandler or CatalogUserAdminAuthenticationHandler ?

We use everywhere (like namespaces) the acronym FA and not CFA/Cfa I guess would make more sense to keep it that way.
CatalogUserAdmin make sense too I guess and it's more readable ? Opinions ?

2022-05-06 08:19 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
> +builder.Configuration.AddJsonFile("appsettings.Docker.json", optional: true, reloadOnChange: true);
Yes I removed the appsettings.Docker file some commits ago. I will find a system that is invisible to the versioning system in local only.

2022-05-06 08:19 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
> +builder.Configuration.AddJsonFile("appsettings.Docker.json", optional: true, reloadOnChange: true);
(Indeed I only need one appsettings at a time)

2022-05-06 09:43 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +        var userId = (string.IsNullOrEmpty(context.Request.Headers["userid"].ToString()) ? "1" : context.Request.Headers["userid"].ToString())!;
Hmm then you receive a nullable string? And we know it's not possible to have a nullable string on that line.

2022-05-06 13:16 UTC, maxime-poulain approved these changes

2022-05-06 13:16 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/FAUserAdminAuthenticationHandler.cs
> +            return AuthenticateResult.Fail(new Exception("An issue occured during authentication"));
```suggestion
            return AuthenticateResult.Fail(new Exception("An issue occurred during authentication"));
```

2022-05-06 15:00 UTC, maxime-poulain requested changes

2022-05-06 16:00 UTC, maxime-poulain approved these changes

2022-05-06 16:01 UTC, merged