Add smart field for super user
smartcoop/smart-cfa pull request #107
Opened 2022-05-03 16:45 UTC by Victor-van-Duijnen

This PR introduces a new IsGivenBySmart field accessible only by super-user in the create and update of a training and includes:
- Validation (only a super user can set the flag)
- A migration for the new field
- Domain model change

https://smartjira.atlassian.net/browse/CFA-334

2022-05-04 07:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
> +                    <smart-checkbox label="@CatalogResources.IsTrainingGivenBySmart" asp-for="CreateTrainingViewModel.IsGivenBySmart"></smart-checkbox>
Download you put a <smart-validation-message /> but you did not here.

2022-05-04 07:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
> +        When(_ => !userIdentity.IsSuperUser, () => RuleFor(viewModel => viewModel.IsGivenBySmart).NotEqual(true).WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType));
```suggestion
        RuleFor(viewModel => viewModel.IsGivenBySmart)
            .Must(BeSuperUser)
            .When(GivenBySmartIsMarked)
            .WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType);      
```
It is always a good practice to use method groups when doing fluent chaining.

2022-05-04 07:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
> +        When(_ => !userIdentity.IsSuperUser, () => RuleFor(viewModel => viewModel.IsGivenBySmart).NotEqual(true).WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType));
```suggestion
        RuleFor(viewModel => viewModel.IsGivenBySmart)
            .Must(BeSuperUser)
            .When(GivenBySmartIsMarked)
            .WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType);      
```
It is always a good practice to use method groups when doing fluent chaining.

2022-05-04 07:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
> +        When(_ => !userIdentity.IsSuperUser, () => RuleFor(viewModel => viewModel.IsGivenBySmart).NotEqual(true).WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType));
Same remark than above.

2022-05-04 07:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
> +        When(_ => !userIdentity.IsSuperUser, () => RuleFor(viewModel => viewModel.IsGivenBySmart).NotEqual(true).WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType));
Same remark than above.

2022-05-04 08:55 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
> +    public void MarkAsGivenBySmart(bool isFromSmart = true )
Should `isFromSmart` default to `true`?

2022-05-04 11:51 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
> +    public void MarkAsGivenBySmart(bool isFromSmart = true )
I believe it does. From the name of the method it appears more clearly. If I write mytraining.MarkAsGivenBySmart(), I should have a training with the flag "IsGivenBySmart".
 It does not mean than a training will be created by default as "GivenBySmart" because the method is actually called by a parameter whose default value is false (but in the case nothing is specified in the signature of the method, seeing its name, it should default to true).

2022-05-04 11:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
> +    public void MarkAsGivenBySmart(bool isFromSmart = true )
Hm going with Mark makes me suppose we got an UnMark, awell we short on time anyway x)

2022-05-04 12:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
> +        RuleFor(viewModel => viewModel.IsGivenBySmart)
Not to be a pain if the ass, I have asked Lieven opinion.
```csharp
        RuleFor(viewModel => viewModel.IsGivenBySmart)
            .Must(BeSuperUser)
            .When(MarkedAsGivenBySmart)
            .WithMessage(CatalogResources.SuperUserPermissionToSetSmartTrainingType);
```

```csharp
private bool BeSuperUser(bool _) => _userIdentity.IsSuperUser;
```

2022-05-04 12:54 UTC, maxime-poulain requested changes
just a little request, awell, if you dont agree fine by me to keep like this :)

2022-05-04 14:53 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
> +    public void MarkAsGivenBySmart(bool isFromSmart = true )
Could you not just use MarkAsGivenBySmart(false)? I am open to suggestion for the naming, though

2022-05-05 07:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
> +        RuleFor(viewModel => viewModel.IsGivenBySmart)
You would have performance gain if there was an out parameter but in this case expect having a discard in the method signature, there's no difference at all.

Since the method is private and the bool is not used I guess it makes sense to have it discarded but on another end it's uglier to read so how's gonna be named the parameter, if you go this way it's entirely up to you :p.

2022-05-05 07:19 UTC, LievenPraet approved these changes

2022-05-05 09:15 UTC, maxime-poulain approved these changes

2022-05-05 09:25 UTC, merged