Add pagination for training list
smartcoop/smart-cfa pull request #112
Opened 2022-05-06 09:38 UTC by NourJammal

CFA
https://smartjira.atlassian.net/browse/CFA-243

Remove chain of depency of classes in guard clause

    Remove specific DomainException in generic predicate guard clause

Transfer collections into Shared project

    We can share some ressources to page a list & validate an email. Those classes previously used in UserAdmin
    project are now available for all CFA projects.
    Change references in AdminUser project.

Add pagination for TrainingList page

    Use shared PagedList.
    Modify Model for the view and add CurrentPage property.
    Adapt html.

Adapt pagination training list in trainer details page

Co-authored-by: NourJammal <naj@smart.coop>
Co-authored-by: ChMelissa <chm@smart.coop>
Co-authored-by: CelineMarique <mar@smart.coop>

2022-05-06 10:19 UTC, maxime-poulain requested changes

2022-05-06 10:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +        var count = await _context.TrainingList
Both of the bellow queries produces the following:
```sql
SELECT [v].[FirstName], [v].[Id], [v].[Language], [v].[LastName], [v].[Title], [v].[TopicId], [v].[TrainerId], [v].[TrainingStatusTypeId]
FROM [Cfa].[v_TrainingList] AS [v]
GO

SELECT [v].[FirstName], [v].[Id], [v].[Language], [v].[LastName], [v].[Title], [v].[TopicId], [v].[TrainerId], [v].[TrainingStatusTypeId]
FROM [Cfa].[v_TrainingList] AS [v]
WHERE ([v].[TrainingStatusTypeId] = 3) AND ([v].[TrainerId] = 1)
GO
```
This means everything is loaded into the memory BEFORE converting to the objects.
It can be very very dangerous over large data set.

Secondly there is no filtering on the Validated status for the count.



another approach could be 
```csharp
	// Query to get a trainer's training ids.
	var trainingIdQuery = V_TrainingList
	.Where(training => training.TrainerId == SomeId && training.TrainingStatusTypeId == ValidatedId)
	.Select(training => training.Id)
	
	// Computes the amont of training that the trainer has.
	var totalTrainerTrainings = await trainingIdQuery.CountAsync();
	
	// Gets the trainer's training list and applies pagination onto it.
	var paginatedIds = trainingIdQuery.Skip(Skip).Take(ItemsPerPage);
	var trainerTrainingList = await V_TrainingList.Where(training => paginatedIds.Contains(training.Id)).ToListAsync();		
```

We could go a bit even further by creating a generic ToPaginate method that could be applied also on the other views.

2022-05-06 10:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml
> +                    <a class="training-list__more-link" asp-page="@Routes.TrainingDetails" asp-route-id=@training.TrainingId>
```suggestion
                        <a class="training-list__more-link" asp-page="@Routes.TrainingDetails" asp-route-id=@training.TrainingId>
```

2022-05-06 10:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml
> +    <div class="u-spacer-xl right">
```suggestion
    <div class="u-spacer-xl">
```

2022-05-06 10:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
> +        var count = await _context.TrainingList.AsAsyncEnumerable().GroupBy(training => training.Id).CountAsync();
Same comments than above

2022-05-06 10:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Smart.FA.Catalog.Showcase.Web.csproj
> +    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
Based on comment I made above this nuget can be removed.

2022-05-06 11:50 UTC, Victor-van-Duijnen commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +        var count = await _context.TrainingList
and as mentionned by @NourJammal the Distinct on the first IQueryable:
`var trainingIdQuery = V_TrainingList
	.Where(training => training.TrainerId == SomeId && training.TrainingStatusTypeId == ValidatedId)
	.Select(training => training.Id)
.Distinct()`

2022-05-06 12:44 UTC, maxime-poulain requested changes

2022-05-06 12:44 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
>      {
You need to handle the cse if CurrentPage is equal or lower than 0 other whise you will get an error:
![image](https://user-images.githubusercontent.com/90202188/167133611-cb4b96be-b850-482e-8fe0-f0051e5dc250.png)

There's multiple way of doing so .
Either you use CurrentPage = Max(CurrentPage, 0) or you just return a 404 if CurrentPage < 0

2022-05-06 12:49 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
> +    <div class="u-spacer-xl right">
Oui la page a été fournie par Violette, mais la partie "toolbar" vient du UserAdmin(du moins je pense).
Il me semble du coup que vous vous êtes inspirées de ca ?
En tout cas hier, nous avons retiré le "right" qui était un leftover de 'u-spacer-xl-right'.
Donc si ca provient bien de la partie UserAdmin, il peut être retiré.

2022-05-06 13:41 UTC, maxime-poulain commented on src/Shared/Smart.FA.Catalog.Shared/Collections/EmailValidator.cs
> -//
I think this is a mistake EmailValidator.cs is moved into the Shared/Collections folder.

2022-05-06 14:04 UTC, maxime-poulain commented on src/Shared/Smart.FA.Catalog.Shared/Collections/Guard.cs
> +        throw new Exception(message);
Ok for @Victor-van-Duijnen  going with ArgumentNull

2022-05-10 09:42 UTC, maxime-poulain approved these changes

2022-05-10 09:48 UTC, merged