Only creators and super users must be able to edit a training
smartcoop/smart-cfa pull request #116
Opened 2022-05-07 15:08 UTC by maxime-poulain

This PR should be reviewed after merge of: https://github.com/smartcoop/smart-cfa/pull/115

Currently any body can edit a training even if he/she isn't the author of that training or a super user.
Note:: having id as primary key didn't help.

2022-05-11 07:56 UTC, Khaon commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> -            var trainers = await _trainerRepository.GetListAsync(request.TrainingId, cancellationToken);
Removed as re-assigning trainers that were already assigned formerly doesn't make much sense.
Also the Trainer.AssignTrainers method just un assign everyone and re-assign them.

2022-05-11 08:02 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> -            training.AssignTrainers(trainers);
Removed as re-assigning trainers that were already assigned formerly doesn't make much sense.
Also the Trainer.AssignTrainers method just un assign everyone and re-assign them.

2022-05-11 10:45 UTC, LievenPraet requested changes

2022-05-11 10:45 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/MustBeSuperUserOrTrainingCreator.cs
> +    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, MustBeSuperUserOrTrainingCreator requirement)
This function should return `Task.CompletedTask;`
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0

2022-05-11 10:45 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.cs
> +        }
We could use return statements instead of if-else clauses
```suggestion
        if (TempData.ContainsKey(ErrorTitleKey))
        {
            ErrorTitle = TempData[ErrorTitle]!.ToString()!;
            return;
        }
        
        if (HttpContext.Items.ContainsKey(ErrorTitleKey))
        {
            ErrorTitle = HttpContext.Items[ErrorTitleKey]!.ToString()!;
            return;
        }
       
       ErrorTitle = CatalogResources.Sorry;
        
```

2022-05-11 10:45 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.cs
> +        }
Same remark as above

2022-05-11 10:45 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/PageModelBase.cs
> +        TempData["ErrorTitle"]   = title;
```suggestion
        TempData["ErrorTitle"] = title;
```

2022-05-11 13:26 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/MustBeSuperUserOrTrainingCreator.cs
> +    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, MustBeSuperUserOrTrainingCreator requirement)
You can't return a Task with the async modifier you need to await [something that returns a task] who result is the output

```csharp
public async Task<T> GetByIdAsync<T>(this DbSet<T> set, int id)
{
   return await set.FirstOrDefaultAsync(item => item.Id = id);
}

public Task<T> GetByIdAsync<T>(this DbSet<T> set, int id)
{
   return set.FirstOrDefaultAsync(item => item.Id = id);
}
```
Above code is the only way to make it compile.

In your example there is no await / async modifier to the method so you must return a task.

David Fowler (creator of ASP net and some other amazing stuff) has written a bit on the subject also.
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task

I always wanted to present a workshop on async / await and Task library, with advanced stuff, now we starting to be back it might be considered

2022-05-12 18:04 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.cs
> +        }
I am not a huge fan in those context to use the return statement just to break the code flow.
I think we should aim to use it in most case to return actual value (it's not a absolute rule ofc).
There's many debate on that topic; where people don't agree but I'd rather keep it that way.

2022-05-12 18:10 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/PageModelBase.cs
> +        TempData["ErrorTitle"]   = title;
thx

2022-05-12 18:11 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/MustBeSuperUserOrTrainingCreator.cs
> +    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, MustBeSuperUserOrTrainingCreator requirement)
All good for you about that ?
It's basic stuff I guess you tried on your own ?

2022-05-13 06:17 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> -            training.AssignTrainers(trainers);
@maxime-poulain If you add a trainer on an existing training (like it was planned at first), you don't have that many choices, either you check all the trainers already linked to the training, you compare with the ids you have in the update request or you unassign all trainers and reassign all the trainers in the update request...

2022-05-13 06:22 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> -            training.AssignTrainers(trainers);
You could just change the implementation of the AssignTrainers method to add a trainer if it doesn't exist on the trainer assignment list of the training, and then assign it. It's not about re-assigning existing trainers, it's about assigning a new trainer for a training already assigned (since it was planned to have multiple trainers for one training).

2022-05-13 06:39 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> +        return request.TrainerIds.Contains(training.CreatedBy);
We had that discussion informally but I supposed you have confirmed with business that only creator of a trainig could update them (not assigned trainers), then?

2022-05-13 06:39 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.cs
> +        }
```suggestion
        if (TempData.TryGetValue(ErrorTitleKey, out var errorTitleKey))
        {
            ErrorMessage = errorTitleKey!.ToString()!;
        }
```
(same for the other if/else statements)

2022-05-13 06:39 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> -            training.AssignTrainers(trainers);
As commented, we will still need a way to assign new trainers but we can see that later anyway.

2022-05-13 08:34 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> -            training.AssignTrainers(trainers);
The current behavior is to just to only allow  creator and super admin no point to support that, furthermore the code code I removed throws an error with the fix.

2022-05-13 08:36 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> +        return request.TrainerIds.Contains(training.CreatedBy);
In the current code the page sends in 

> new TrainingIds {  currentUserId  }
I don't see myself starting rewritting the whole web logic for the time being.

2022-05-13 08:49 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
> +        return request.TrainerIds.Contains(training.CreatedBy);
Okok good point. We will see that later

2022-05-13 09:21 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.cs
> +        }
As stated i call wont be doing this.

2022-05-13 11:14 UTC, LievenPraet approved these changes

2022-05-13 12:02 UTC, merged