Standarize paging super user
smartcoop/smart-cfa pull request #128
Opened 2022-05-10 15:51 UTC by Victor-van-Duijnen

In previous PR, a change of the paging of trainings broke the paging of the super user but was left untested.
Here is a hotfix to make an unified system for the paged list.

2022-05-10 21:57 UTC, Khaon requested changes

2022-05-10 21:57 UTC, Khaon commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/PagedListExtension.cs
> +    public static async Task<PagedList<T>> PaginateAsync<T>(this IQueryable<T> source, PageItem pageItem, CancellationToken cancellationToken)
You pass the token but you don"t pass it down to the ToListAsync method.
Make it optional i.e. CancellationToken cts = default

I made a misstake but every cancellation tokens should be optional.

2022-05-10 21:57 UTC, Khaon commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml
> +            <div>Page @(Model.Trainings.PageIndex + 1)/@(Model.Trainings.TotalPages.ToString())</div>
You should switch to the CurrentPage of yours instead of +1 on PageIndex.
PageIndex in the late implementation PaginatedList you removed is the equivalent of the CurrentPage.

2022-05-11 07:52 UTC, maxime-poulain approved these changes

2022-05-11 07:54 UTC, Khaon approved these changes

2022-05-11 07:59 UTC, merged