Persist the first name, last name and email address of a trainer using data sent by account in the HTTP headers
smartcoop/smart-cfa pull request #129
Opened 2022-05-10 18:36 UTC by maxime-poulain

Account put in the HTTP headers the first name, last name and email address of the current user.
This commit persist that information in the trainer table.

2022-05-10 21:43 UTC, Khaon commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainerIdentityCommand.cs
> +/// Updates the first name, last name and email of a <see cref="Trainer" />
```suggestion
/// Updates the first name, last name and email of a <see cref="Trainer" />.
```

2022-05-10 21:49 UTC, Khaon requested changes

2022-05-10 21:49 UTC, Khaon commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainerIdentityCommand.cs
> +/// <param name="LastName">The last name of the trainer.</param>
```suggestion
/// <param name="LastName">The trainer's last name.</param>
```

2022-05-10 21:49 UTC, Khaon commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainerIdentityCommand.cs
> +            .FirstAsync(trainer => trainer.Id == command.TrainerId, cancellationToken: cancellationToken);
```suggestion
            .FirstAsync(trainer => trainer.Id == command.TrainerId, cancellationToken);
```

2022-05-11 08:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +        //if (!headerDictionary.ContainsKey("X-Accel-Redirect") || !headerDictionary.ContainsKey("X-Real-Location"))
That question is more for you @Victor-van-Duijnen

2022-05-11 08:14 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +        //if (!headerDictionary.ContainsKey("X-Accel-Redirect") || !headerDictionary.ContainsKey("X-Real-Location"))
@maxime-poulain No no, those headers are removed when the call is redirected to cfa (so cfa never sees them).

2022-05-11 08:16 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +        //if (!headerDictionary.ContainsKey("X-Accel-Redirect") || !headerDictionary.ContainsKey("X-Real-Location"))
Ok good, thx. that's what i was afraid of x).
I'll remove the comment.

2022-05-11 09:37 UTC, Khaon approved these changes

2022-05-11 10:33 UTC, LievenPraet approved these changes

2022-05-11 10:50 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +            Context.Request.Headers.Add("FirstName", "John");
@maxime-poulain Sorry I realise I didn't tell you that but the FirstName, LastName and Email (with that casing) fields are passed in a "customData" header as a json object which is url encoded (if you want I already have an example for that since I had started it or I can even push a commit on your branch if you don't mind).

2022-05-11 10:59 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
> +            Context.Request.Headers.Add("FirstName", "John");
As you wish either you provide me the json or you add a commit that handles correctly

2022-05-11 14:37 UTC, maxime-poulain commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/CustomData.cs
> +        var serializedCustomData = JsonConvert.SerializeObject(customData);
```suggestion
        var serializedCustomData = JsonSerializer.Serializet(customData);
```

2022-05-11 14:40 UTC, maxime-poulain commented
@Victor-van-Duijnen 
Overall I am not a huge fan of having any class just named "Custom" something.
Like the following class
> CustomData 
As the reviewer, I know what's behind but for anyone it will be definitely confusing.

2022-05-11 14:44 UTC, Victor-van-Duijnen commented
@maxime-poulain I don't like it that much either but in that case, "CustomData" is the name of the header of a library that we cannot modify (or it is outside the scope of the PR).

2022-05-11 14:45 UTC, maxime-poulain commented
I don"t think its a problem you can decorate the property to CustomData and comment 
Or even better
Add a summary over someting like AccountData class that says the name in the headers is CustomData

2022-05-12 07:50 UTC, LievenPraet requested changes

2022-05-12 07:50 UTC, LievenPraet commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/AccountData.cs
> +            case "2":
Case 2 can be removed since it is empty, It will be handled by the `default` case.

2022-05-12 07:50 UTC, LievenPraet commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/Pages/cfa.cshtml.cs
> +        HttpContext.ProxyRedirect("/", id, AccountataFactory.GetByUserId(id).Serialize());
```suggestion
        HttpContext.ProxyRedirect("/", id, AccountDataFactory.GetByUserId(id).Serialize());
```

2022-05-12 07:50 UTC, LievenPraet commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/Pages/cfa.cshtml.cs
> +        HttpContext.ProxyRedirect("/", id, AccountataFactory.GetByUserId(id).Serialize());
The name factory is not correct here. It doesn't create anything. You just access the function `GetByUserId`.

2022-05-12 07:50 UTC, LievenPraet commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/ProxyRedirect.cs
> +    public static void ProxyRedirect(this HttpContext context, string page, string userId, string customData)
`AccountData` is a better name than `CustomData` because it indicates better what type of data it is

2022-05-12 07:50 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/AccountData.cs
> +public static class AccountDataFactory
```suggestion
public static class AccountDataService
```

2022-05-12 07:50 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/AccountData.cs
> +public static class AccountDataFactory
We can also make it non static and use DI to inject it when needed

2022-05-12 07:50 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/Headers.cs
> +    public const string AccountData = "customData";
Why not call it `accountData`?
```suggestion
    public const string AccountData = "accountData";
```

2022-05-12 07:59 UTC, Victor-van-Duijnen commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/Pages/cfa.cshtml.cs
> +        HttpContext.ProxyRedirect("/", id, AccountataFactory.GetByUserId(id).Serialize());
Good catch, will change the name!

2022-05-12 07:59 UTC, Victor-van-Duijnen commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/AccountData.cs
> +            case "2":
I had seen that,  but I would really prefer to be explicit that the userid "2" would go in the default statement (and that there exists an user id "2")

2022-05-12 08:02 UTC, Victor-van-Duijnen commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/ProxyRedirect.cs
> +    public static void ProxyRedirect(this HttpContext context, string page, string userId, string customData)
Yes I will change the variable name to accountData in that case. The "customData" naming derives from the name I receive from Nginx header passed by Anthony's library (which cannot be changed).

2022-05-12 08:41 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/Headers.cs
> +    public const string AccountData = "customData";
As mentionned the name of the header cannot be changed. It's part of the library created by Anthony. It's the general name to pass specific data that are not part of the default header (like userid and smartapplication)

2022-05-12 13:13 UTC, Victor-van-Duijnen commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/ProxyRedirect.cs
> +    public static void ProxyRedirect(this HttpContext context, string page, string userId, string customData)
No actually it's better in that case I let customData since the header is named like that. I have renamed it in the whole project CFA as AccountData so that we know from which application it is coming from but the name of that var inside the account context has to reflect the header it will pass down to nginx.

2022-05-12 13:46 UTC, maxime-poulain commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/ProxyRedirect.cs
> +    public static void ProxyRedirect(this HttpContext context, string page, string userId, string customData)
it makes it clear to you as you develop that but for anyone that just lands in it won't be the case.

2022-05-12 13:46 UTC, maxime-poulain commented on src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/AccountData.cs
> +    }
I noticed that you have a serializedAccountData below so I guess it should be named the same here.
```suggestion
    public static string Serialize(this AccountData accountData)
    {
        var serializedAccountData = JsonSerializer.Serialize(accountData);
        return System.Web.HttpUtility.UrlDecode(serializedAccountData );
    }

    public static AccountData? Deserialize(string serializedAccountData)
    {
        if (string.IsNullOrEmpty(serializedAccountData))
        {
            return new AccountData();
        }

        return JsonSerializer.Deserialize<AccountData?>(serializedAccountData );
    }
```

2022-05-12 15:00 UTC, LievenPraet requested changes
Still see comments that not have been changed

2022-05-13 08:10 UTC, LievenPraet approved these changes

2022-05-13 08:18 UTC, merged