Replace pre-signed image by public url
smartcoop/smart-cfa pull request #141
Opened 2022-05-12 10:22 UTC by Victor-van-Duijnen

This PR replaces pre-signed image by public url. The image's path are hashed but publically accessible, limiting the number of calls to the application and its performance.

2022-05-12 13:17 UTC, LievenPraet requested changes

2022-05-12 13:17 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
> +public class MinIoLinkGenerator : IMinIoLinkGenerator
Service might be a better name to stay consistent in our naming
```suggestion
public class MinIoLinkService : IMinIoLinkService
```

2022-05-12 13:17 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/IMinIoLinkGenerator.cs
> +public interface IMinIoLinkGenerator
```suggestion
public interface IMinIoLinkService
```

2022-05-12 13:17 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
> +                                <img src="@(UserIdentity.CurrentTrainer.ProfileImagePath is null ? MinIoLinkGenerator.GetFullTrainerProfilePictureUrl(MinIoLinkGenerator.GetDefaultFullProfilePictureIm
We could create a local function to make the code a bit more readable

2022-05-12 13:49 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
> +public class MinIoLinkGenerator : IMinIoLinkGenerator
I suggested Victor that name, I think it is good as it makes it clear what it does.
An example:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.passwordhasher-1?view=aspnetcore-6.0

However MinIOService we have does a bunch of different things it makes sense have suffix.

You will also most likely name a service that provides IConnection IConnectionProvider.

2022-05-12 13:52 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
> +                                <img src="@(UserIdentity.CurrentTrainer.ProfileImagePath is null ? MinIoLinkGenerator.GetFullTrainerProfilePictureUrl(MinIoLinkGenerator.GetDefaultFullProfilePictureIm
Two solutions here:
MinIoLinkGenerator.GetCurrentTrainerProfilePictureUrl() that uses the Current User Identity service to retrieves dynamically the URL with a fallback of the defualt one

OR

MinIoLinkGenerator.GetFullTrainerProfilePictureUrl(string path)=> if null return default;

But what's it is sure is that that line has too much logic.

2022-05-12 14:04 UTC, maxime-poulain requested changes

2022-05-12 14:04 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/IMinIoLinkGenerator.cs
> +    /// <returns>The relative url to the profile picture of the trainer</returns>
It's more of a path nope?

2022-05-12 14:04 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
> +        return Path.Combine("trainers/", "profile-image/", $"{hashIds.Encode(trainerId)}{imageFormat}");
If you don't like putting that in the configuration files (fine by me) you should, i think, extract them in private constant at the top of the class

2022-05-12 17:36 UTC, maxime-poulain approved these changes

2022-05-13 08:13 UTC, LievenPraet approved these changes

2022-05-13 08:27 UTC, merged