Feature/wording alignement and redirection
smartcoop/smart-cfa pull request #175
Opened 2022-05-16 16:11 UTC by Victor-van-Duijnen

2022-05-16 17:18 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +            options.LowercaseQueryStrings = true;
If you got a query string used for some search that is case sensitive how does that gonna behave with this setting to true?

2022-05-17 07:04 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +            options.LowercaseQueryStrings = true;
It only affect the key of the query parameters, not the values. So it will work fine!

2022-05-17 07:24 UTC, maxime-poulain approved these changes

2022-05-17 08:32 UTC, maxime-poulain requested changes
C:\Users\pam\Pictures\Screenpresso\video_08.mp4

The querystring's values are also set to lower case.

2022-05-17 08:36 UTC, maxime-poulain requested changes

2022-05-17 08:36 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +        mvcBuilder.Services.Configure<RouteOptions>(options =>
I guess we should use the AddRouting extensionss method:
[    public static IServiceCollection AddRouting(](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Http/Routing/src/DependencyInjection/RoutingServiceCollectionExtensions.cs#L113) rather then that one.

Note both of them are extensions on IServiceCollection not MvcBuilder.

2022-05-17 08:39 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +        mvcBuilder.Services.Configure<RouteOptions>(options =>
Ah no that's not a query string parameter, a query string parameter has the form "?parameterstring=xxx". On your example it's part of the route unfortunately so indeed that's set to lowercase

2022-05-17 09:58 UTC, maxime-poulain approved these changes

2022-05-17 09:59 UTC, merged