Add search in training page
smartcoop/smart-cfa pull request #178
Opened 2022-05-18 07:53 UTC by NourJammal

# CFA > Training page

Add search bar
Add Topic filters

https://smartjira.atlassian.net/browse/CFA-270

2022-05-18 09:36 UTC, maxime-poulain requested changes

2022-05-18 09:36 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
> +    public static async Task<PagedList<TrainingList>> SearchPaginatedTrainingsAsync(this IQueryable<TrainingList> query,
```suggestion

    public static async Task<PagedList<TrainingList>> SearchPaginatedTrainingsAsync(this IQueryable<TrainingList> query,
```

2022-05-18 09:36 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
> +    public static async Task<PagedList<TrainingList>> SearchPaginatedTrainingsByTopicAsync(this IQueryable<TrainingList> query,
```suggestion

    public static async Task<PagedList<TrainingList>> SearchPaginatedTrainingsByTopicAsync(this IQueryable<TrainingList> query,
```

2022-05-18 09:36 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/ITrainingService.cs
> +    public Task<PagedList<TrainingListViewModel>> SearchTrainingByTopicViewModelsAsync(int? searchTopicId, int currentPage, int pageSize);
Une meilleure signature serait
> SearchTrainingViewModelsByTopicAsync
> or
> SearchTrainingViewModelsByTopicIdAsync

De cette manière tu annonces clairement que ce sont des training view model qui sont retournés et pas des trainings cherché par des topic view models.

2022-05-18 14:12 UTC, LievenPraet requested changes

2022-05-18 14:12 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
> +            query = query.Where(trainingList => trainingList.Topic == searchTopic);
Same lowercase remark here

2022-05-18 14:12 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
> +        Trainings = await _trainingService.SearchTrainingViewModelsAsync(searchKeyword, CurrentPage, ItemsPerPage);
Any reason to include ViewModel in the function name?
```suggestion
        Trainings = await _trainingService.SearchTrainingsAsync(searchKeyword, CurrentPage, ItemsPerPage);
```

2022-05-18 14:12 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
> +        Trainings = await _trainingService.SearchTrainingViewModelsByTopicIdAsync(id, CurrentPage, ItemsPerPage);
Same remark as above

2022-05-18 14:14 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
> +                                                trainingList.Methodology.Contains(searchKeyWord));
It's a IQueryable therefore it's okay as sql is case insensitive.

2022-05-18 14:15 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
> +            query = query.Where(trainingList => trainingList.Topic == searchTopic);
This is an enumeration therefore, the value is an integer.

2022-05-19 07:37 UTC, LievenPraet approved these changes

2022-05-19 10:48 UTC, maxime-poulain approved these changes

2022-05-19 11:00 UTC, merged