UserAdmin: SuperUserTrainingList: add support for searching trainings by training creator name
smartcoop/smart-cfa pull request #180
Opened 2022-05-18 18:40 UTC by maxime-poulain

… by training creator name

Now super users can filter when searching by a trainer's name.

2022-05-19 07:35 UTC, LievenPraet requested changes

2022-05-19 07:35 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
> +    private IQueryable<Training> BaseQuery()
```suggestion
    private IQueryable<Training> GetBaseQuery()
```

2022-05-19 10:50 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
> +    private IQueryable<Training> BaseQuery()
I tend to put a "Get" prefix on method that gonna fetch one way or another some kind of resource.
"GetTrainerById" -> from db
"GetCountryList" => from an API or so.
To me, it makes it clear that we are fetching something and there's an underlying IO operation under the hood.

I might turn that into a public get property however ?

2022-05-19 11:00 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
> +    private IQueryable<Training> BaseQuery()
To me, a function should represent an action: get, insert, delete, convert, send...
IN this case, a property might be a better choice here

2022-05-19 11:02 UTC, LievenPraet requested changes
See comments above

2022-05-25 08:47 UTC, Victor-van-Duijnen approved these changes

2022-05-25 10:19 UTC, merged