Rewrite minio handler
smartcoop/smart-cfa pull request #187
Opened 2022-05-23 09:00 UTC by Victor-van-Duijnen

This PR refactor the profile picture form part of the profile page to:

- Separate the call from the rest of the form
- Generate an unique hash at each upload to avoid browser caching

2022-05-23 10:08 UTC, maxime-poulain requested changes

2022-05-23 10:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
> +    [BindProperty] public EditProfileCommand? EditProfileCommand { get; set; }
Do you mind keep the attribute above the property ?

It is already the case

2022-05-23 10:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
> +        return hasErrors ? RedirectToPage() : Page();
Redirecting to the current page is probably not something you want to happen in case of failure.

2022-05-23 10:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UploadTrainerProfileImageCommand.cs
> +            .Must(IsUnderMaxSize).WithMessage(CatalogResources.ProfilePage_Image_FileTooBig)
I suggest replacing IsUnderMaxSize with BeUnderMaxSize.
Do you mind putting one dot per line ?

2022-05-23 10:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UploadTrainerProfileImageCommand.cs
> +            .MustAsync(IsCorrectTypeAsync).WithMessage(CatalogResources.ProfilePage_Image_WrongFileType);
same than above about the "Is" => "Be"

2022-05-23 10:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
> +        var hashIds = new Hashids(Guid.NewGuid().ToString(), 16);
```suggestion
        var hashIds = new Hashids(salt: Guid.NewGuid().ToString(), 16);
```
Not storing the Guild.NewGuid in a '"var salt" variable is not intuitive therefore adding the argument will give more insight.

2022-05-25 08:35 UTC, LievenPraet approved these changes

2022-05-25 12:20 UTC, maxime-poulain approved these changes

2022-05-25 12:27 UTC, merged