Add popup contact in trainer card
smartcoop/smart-cfa pull request #190
Opened 2022-05-24 11:21 UTC by joe-coop

- Add localization keys
- Add Mono js general file
- Add some css to the link to the personal contact form
- Add link to personal contact form and the html popup

2022-05-24 11:23 UTC, joe-coop commented
Maxime je n'ai ajouté que la structure html pour le popup. Il devra inclure le formulaire de contact : identique au formulaire de contact général avec envoi vers le mail du formateur

2022-05-25 08:20 UTC, LievenPraet requested changes

2022-05-25 08:20 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/wwwroot/js/modules/bundle-client.js
> +
Same remark as above about js extensions

2022-05-25 15:41 UTC, LievenPraet approved these changes

2022-05-30 10:16 UTC, maxime-poulain approved these changes

2022-05-30 10:16 UTC, merged