Add Soft delete to entities
smartcoop/smart-cfa pull request #213
Opened 2022-06-03 10:56 UTC by Victor-van-Duijnen

This PR introduces soft delete to entities, it allows:

- Entities to be destroyed (hard delete) with the Destroy() method
- Entities to be soft deleted with the Delete() method
=> It follows that I have used the flag IsDeleted to flag an entity as soft deleted

- It adds a global query filter on class deriving from the Entity class in user admin 
- It filters out soft deleted entities in sql views in showcase

2022-06-03 11:41 UTC, LievenPraet requested changes

2022-06-03 11:41 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220603102434_Filter_On_SoftDelete.cs
> +                WHERE TrainingStatusType.Name = 'Published'
Did we forget to check to `IsDeleted` flag here?

2022-06-03 11:41 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220603102434_Filter_On_SoftDelete.cs
> +                WHERE TrainingStatusType.Name = 'Published'
Same remark as above

2022-06-03 11:41 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220603102434_Filter_On_SoftDelete.cs
> +                WHERE TrainingStatusType.Name = 'Published'");
Same remark as above

2022-06-03 11:41 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220603102434_Filter_On_SoftDelete.cs
> +                WHERE TrainingStatusType.Name = 'Published'");
Same remark as above

2022-06-03 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/IEFSoftDelete.cs
> +public interface IEFSoftDelete
I would suggest adding the full name of EF here for clarity.
```suggestion
public interface IEntityFrameworkSoftDelete
```

2022-06-03 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/IEFSoftDelete.cs
> +public interface IEFSoftDelete
On second thought, shouldn't it be called `IEntitySoftDelete`?

2022-06-03 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Core/SeedWork/Entity.cs
> +    public void Destroy() => IsDestroyed = true;
Wouldn't destroying the entity mean deleting it entirely from the database?
The functions `Delete` and `Destroy` now basically do the same job and are redundant.

2022-06-03 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/SoftDeleteQueryExtension.cs
> +        var filter = methodToCall.Invoke(null, Array.Empty<object>());
Do we need to use reflection here?
It screws up IntelliSense and complicates the code.
Is there another way we could do this?

2022-06-03 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/CatalogContext.cs
> +            // The IsDestroyed flag allow to force hard delete to the entity
Why implement this on `ModelCreating`?
Can't we just delete the entity at the time we would set the `IsDestroyed` flag to true?

2022-06-03 12:06 UTC, maxime-poulain commented
The concept feels a bit akward to me; having the entities responsible to determine their delete state feels strange.

To me, deleting / softdeleting should be completly the responsablity of your DAL (db context, uow, w/e).

Did you inspire on some resource you might point to have a look at ?

2022-06-03 12:30 UTC, Victor-van-Duijnen commented
In all of the references I have seen, they don't use methods but they have a public property IsDeleted on their object, which is the same as to expose a Delete methods because an object could still be responsible for its own destruction (myObject.IsDeleted = true, but then I would rather go with a declarative style like for all of our rich domain models than a public property) refs: https://www.thereformedprogrammer.net/ef-core-in-depth-soft-deleting-data-with-global-query-filters ; https://spin.atomicobject.com/2019/01/29/entity-framework-core-soft-delete ; https://medium.com/@uslperera/soft-delete-with-ef-core-c677bff73ef7... Conceptually it doesn't bother me personally because an entity is already modifying all of its properties and a soft delete is just another state of an object. Maybe we can find a compromise if the Destroy(hard delete) method is moved to an overload of specific db sets...

2022-06-03 12:35 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/IEFSoftDelete.cs
> +public interface IEFSoftDelete
Yes I am not too fond of my name either retrospectively. Why not IEntitySoftDelete indeed but what do you say about simplifying it to `ISoftDelete `?

2022-06-03 13:16 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/IEFSoftDelete.cs
> +public interface IEFSoftDelete
Yes, I was think ing about that after my remark as well :D
Make it `ISoftDelete`

2022-06-03 13:22 UTC, maxime-poulain commented
There is also an important case to be taken in account.
When you soft delete you save the entity.
However if someone changes an object than just call softdelete, the other column will be updated in the database.
I guess that's something we don't want.

2022-06-07 07:09 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Core/SeedWork/Entity.cs
> +    public void Destroy() => IsDestroyed = true;
It was decided that we will remove the Destroy method to keep YAGNI principle :)

2022-06-07 08:34 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/SoftDeleteQueryExtension.cs
> +    public static void AddSoftDeleteQueryFilter(this ModelBuilder modelBuilder)
You could do something better like this:
```csharp
public static void SetFilterQueryOnEntityDerivedFrom<T>(this ModelBuilder modelBuilder, Expression<Func<T, bool>> query)
{
    foreach (var mutableEntityType in modelBuilder.Model.GetEntityTypes().Where(entity => entity.GetType().IsAssignableTo(typeof(T))))
    {
        // At runtime the parameter type is expected to be `mutableEntityType.ClrType` but query's type if T.
        // So we need to revisit the expression tree to change the parameter type to the actual entity type.
        var actualEntityTypeParameter = Expression.Parameter(mutableEntityType.ClrType);
        var body = ReplacingExpressionVisitor.Replace(query.Parameters.First(), actualEntityTypeParameter, query.Body);
        var lambdaExpression = Expression.Lambda(body, actualEntityTypeParameter);

        mutableEntityType.SetQueryFilter(lambdaExpression);
    }
}

// usage :
modelBuilder.SetFilterQueryOnEntityDerivedFrom<IEntity>(e => e.Id < 5);
```

2022-06-17 12:24 UTC, Victor-van-Duijnen commented
Following the COPBACK it was decided we might close this PR since it was found the complexity was not worth it.
Before closing it definitively I would just like to have your comment @Geraldineb1 @pierrewatelet @BomUbik @JOABAUDENS so it doesn't look like a whim on my part.

2022-06-17 13:03 UTC, maxime-poulain commented
You an close it but we can go back at some point get the impl for the global query filtering, etc as the implementation is already there.

I doubt that among all the person you tagged, me and you would forgot something had already be done.

2022-06-17 13:04 UTC, closed without merging