Add support for rich text editors.
smartcoop/smart-cfa pull request #240
Opened 2022-06-22 18:31 UTC by maxime-poulain

This PR is a follow up of https://github.com/smartcoop/smart-cfa/pull/239

This PR introduces a rich text editor for the creation/edition of trainings.
After discussion quill has been chosen.
A quick list / overview of existing popular library can be seen [here](https://github.com/jaredreich/pell#comparisons).

It would not be too much complicated to change to another library. 
However those point need to be discussed:

- What size should we give by default to those editors ?
- Do we need to customize a bit the css ?

Here is a quick demo how it looks like, for the time being.

https://user-images.githubusercontent.com/90202188/175110419-dba23ca3-2b38-47bf-9289-3a598b20c4b7.mp4

2022-06-23 11:41 UTC, LievenPraet requested changes

2022-06-23 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml.cs
> +        var response = await Mediator.Send(createTrainingRequest);
The var for the request has details in the name but the response does not.
We should choose 1 approach and be consistent with it.
```suggestion
        var request = CreateTrainingViewModel.MapToRequest(UserIdentity.CurrentTrainer.Id, UserIdentity.CurrentTrainer.DefaultLanguage);
        var response = await Mediator.Send(createTrainingRequest);
```

2022-06-23 11:41 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Shared/_TrainingCreationEditionForm.cshtml
> +</script>
We need to eventually create a RTE component in the design library and move the js there

2022-06-23 11:55 UTC, Victor-van-Duijnen commented
You can fix the broken bold font of the text editor by adding the css
 ` .ql-editor strong{
         font-weight:bold;
     }`

2022-06-23 12:27 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        if (node.nodeName == "div" || node.nodeName == "DIV") {
```suggestion
        if (node.nodeName === "div" || node.nodeName === "DIV") {
```

2022-06-23 12:27 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        if (node.nodeName == "div" || node.nodeName == "DIV") {
Do we want to be able to send a form with the enter key from a div like the title of a training?

2022-06-23 12:27 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        var node = (e.target) ? e.target : ((e.srcElement) ? e.srcElement : null);
Suggested by the IDE: 
```suggestion
     var e = (e) ? e : ((Event) ? Event : null);
        var node = (e.target) ? e.target : ((e.target) ? e.target : null);
```
But more seriously, I seem to have the same behaviour with or without the method (tested on the training page only in Chrome and FIrefox in private mode). Is the enter key event blocked by default with the rich text editor fields (in quill) . Just mentionning it because I found it strange, is it the same for you @maxime-poulain ?

2022-06-23 14:30 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Shared/_TrainingCreationEditionForm.cshtml
> +    var superUser = identityService.IsSuperUser;
Was hard to think properly yday x).
I am gonna inject directly the service instead of using the service locator

2022-06-23 14:31 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Shared/_TrainingCreationEditionForm.cshtml
> +</script>
Yes but I guess let's wait to see if emily has something else to propose ?

2022-06-23 14:32 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        //RegisterCultureChange();
Yup it looks for a <select> that doesnt exist (at least it is commented too).

2022-06-23 14:32 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        if (node.nodeName == "div" || node.nodeName == "DIV") {
It's just to have the break line working.

2022-06-23 14:38 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        var node = (e.target) ? e.target : ((e.srcElement) ? e.srcElement : null);
Hm we loose the falback to srcElement doing so

2022-06-24 09:23 UTC, chastelain commented
- Isn't the question of character limitation a database-side problematic?
- Allowing rich-text input, is XSS being taken into account? In DeskAPI we use this package to clean 
text inputs: https://github.com/Vereyon/HtmlRuleSanitizer
- > but its flaws:
"you must arrrive >>>>>>>>>>>>>>>>>> there";
the >>>>>>>> would be removed.

You sure?

![image](https://user-images.githubusercontent.com/6050181/175505726-f84cee83-972a-439c-bde1-9ea2ef2ab568.png)

2022-06-24 09:30 UTC, maxime-poulain commented
> Isn't the question of character limitation a database-side problematic?
What do you exactly mean ? With the correct validation it would not 

>  Allowing rich-text input, is XSS being taken into account?
No, not at all ! I will look into that 

> You sure?
Heh, yes, I didn't post the actual example I tried x)
![image](https://user-images.githubusercontent.com/90202188/175507320-cafe42db-e3b3-4a1d-a372-bb1d7083c6a1.png)

2022-06-24 10:22 UTC, chastelain commented
> > Isn't the question of character limitation a database-side problematic?

> What do you exactly mean ? With the correct validation it would not

I mean historically in our databases, text columns have always been constrained to a max fixed value, I don't know if it's something that has to be considered for CFA or not, but with no limitation, no problem.
However, if you strip the HTML on the input, aren't you saving the text in the DB without the formatting? How would you "unstrip" it back?
Or is it just to bypass an input validation on char counting?

> You sure?

>> Heh, yes, I didn't post the actual example I tried x)

Didn't try with `<` inside html text tags xD My bad.

2022-06-24 10:45 UTC, Victor-van-Duijnen commented
@chastelain It's only for validation, the actual string stored will contain the metadata but it's true that, besides the actual content of a RTF, we should maybe also validate the size of the text + metadata (someone could send really really big strings full of metadata but no actual text). For example, we need to have a minimum of 30 characters for some fields (business rule). If we make the check on the complete string, it won't work properly.

@maxime-poulain Looking at quill's issues, I found that thread: https://github.com/quilljs/quill/issues/1918 and they seem to recommend https://github.com/apostrophecms/sanitize-html to prevent XSS.

It's true that it doesn't look that easy to find a regex that only take the string between matching html tags :'(

2022-06-28 07:13 UTC, maxime-poulain commented
> @chastelain It's only for validation, the actual string stored will contain the metadata but it's true that, besides the actual content of a RTF, we should maybe also validate the size of the text + metadata (someone could send really really big strings full of metadata but no actual text). For example, we need to have a minimum of 30 characters for some fields (business rule). If we make the check on the complete string, it won't work properly.
> 
> @maxime-poulain Looking at quill's issues, I found that thread: [quilljs/quill#1918](https://github.com/quilljs/quill/issues/1918) and they seem to recommend https://github.com/apostrophecms/sanitize-html to prevent XSS.
> 
> It's true that it doesn't look that easy to find a regex that only take the string between matching html tags :'(

We need to have the sanitization at the back end level, quil js already escapes, however, the things that could lead into a XSS.

2022-06-28 07:22 UTC, maxime-poulain commented
@Victor-van-Duijnen 
@chastelain 
@LievenPraet 
Sup guys,

after struggling, I finally seem to reach an acceptable solution.

# First, summary of issues:
The deskAPI uses a custom resolver that applies sanitization on every string but one marked with a given attribute (something like [IgnoreSanitization].

Sadly, and as expected x), we cannot use that approach (at least with System.Text.Json, I think it could have been done with Newton but the best is not to use that lib anymore).

* We are posting forms and the actual type are form data and not JSON.
* Starting to manually apply sanitization on properties seems to be retarded.

# Solution:

I don't think having everything sanitized is a good way we might break stuff that are not intended to.
After some digs, the best library to do sanitization is https://github.com/mganss/HtmlSanitizer

I could figure out how to add a custom ModelBinder and Provider that changes the default behavior of binding on string that have an attribute

> [Sanitized]

So the API that PR might introduce looks like this:

```csharp
public class EditProfileCommand : IRequest<ProfileEditionResponse>
{
    public int TrainerId { get; set; }

    [Sanitized]
    public string? Bio { get; set; }

    [Sanitized]
    public string? Title { get; set; }

    public Dictionary<int, string>? Socials { get; set; }
}
```

Both **Bio** and **Title** get sanitized


# Last: validation, what to do with that ! ?
Now we are posting HTML  + CSS attribute the strings become super long but the validation still needs to be working properly.

There's two ways I could identity:

1.  Simple Regex escaping ( <div>hello toto <<<<<<<<<<< ?? </div> will result in hello toto, heh.
2. Track HTMLAgilityPack that will do that properly. (We get like a factory for a simple thing tho ;( );


 ## Comments ?

2022-06-28 10:17 UTC, Victor-van-Duijnen commented
@maxime-poulain For sanization I am not sure what were the criteria for chosing that specific library but I will trust your choice on it. I would indeed not have recommended sanization everywhere by default and custom model binding seems right to me.

For the validation part, HtmlAgilityPack might be the best solution when it comes to result but it also comes with a lot of baggages which I am not too fond of. Just to be sure I understand we can not do much better than the regex that will scrap everything after "<" even if it's not a tag? If we really can't do otherwise, then HtmlAgilityPack...

2022-06-28 12:22 UTC, maxime-poulain commented
> @maxime-poulain For sanization I am not sure what were the criteria for chosing that specific library but I will trust your choice on it. I would indeed not have recommended sanization everywhere by default and custom model binding seems right to me.
> 
> For the validation part, HtmlAgilityPack might be the best solution when it comes to result but it also comes with a lot of baggages which I am not too fond of. Just to be sure I understand we can not do much better than the regex that will scrap everything after "<" even if it's not a tag? If we really can't do otherwise, then HtmlAgilityPack...

Regarding the library there aren't out there. However it is the most recent one and it is very flexible.
There was the one they used in the DeskApi but it has not been updated for more than one year.

Back to the current lib:
![image](https://user-images.githubusercontent.com/90202188/176176612-e357f765-738c-4565-88de-97546c3052d4.png)

I went with the default config maybe in the future that might need to be adjusted 

Regarding validation:

> hello toto <<<<<<<<<<< ??

will become 

> hello toto

I don't mind going with the regex it is faster. Note that one of the reason i did not want to go with DeskApi's one it is because it uses HtmlAgilityPack under the hood x).

I can write some kind of benchmark also to compare regex vs HTmlPack to validate the number of chars.

2022-06-29 10:58 UTC, chastelain commented
IMO you're focusing on performance when there's no real need and it's no game changer.

Using regex will be faster but in return the output may not be correct. 
It just takes one bug ticket from a user who really wants to format its text with `<<<<<` to make us change its behaviour lately xD

Is it really necessary to sanitize? ASP Core doesn't offer already some mechanisms? https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-6.0

Is it really bad to use HAP?

2022-06-29 12:59 UTC, maxime-poulain commented
We need to use some ways to decode HTML (HtmlString or @HTml.Raw) to render correctly the HTML and not the escaped one.

QuilLJS escapes already for use <scirpt> to &:ltscript&:gt but this is not enough as anyone could simply use postman or something else to send some data.

like stated : ASP.NET Core MVC provides an HtmlString class which isn't automatically encoded upon output. This should never be used in combination with untrusted input as this will expose an XSS vulnerability.

https://user-images.githubusercontent.com/90202188/176441359-168d5aed-4cfd-4737-94dc-e4c3114b508f.mp4

2022-07-01 14:26 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml.cs
> +        var response = await Mediator.Send(createTrainingRequest);
That was updated and set a meaningful name.

2022-07-01 14:27 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +        var node = (e.target) ? e.target : ((e.srcElement) ? e.srcElement : null);
I see i have adjusted a bit the JS code based on this feedbck.

2022-07-04 10:19 UTC, chastelain approved these changes

2022-07-04 10:50 UTC, LievenPraet approved these changes

2022-07-04 10:55 UTC, chastelain commented
>> IMO you're focusing on performance when there's no real need and it's no game changer.
>> 
>> Using regex will be faster but in return the output may not be correct. It just takes one bug ticket from a user who really wants to format its text with <<<<< to make us change its behaviour lately xD
>> 
>> Is it really necessary to sanitize? ASP Core doesn't offer already some mechanisms? https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-6.0
>> 
>> Is it really bad to use HAP?

>> 

> @chastelain For the record, I was not suggesting that we use a sub-par (namely the regex mentioned) solution because I was afraid of the performance of HtmlAgilityPack, I wanted to confirm that there wasn't other regex/way to cover that use case, without having to import a library that contains a lot of things we don't need.

Mmmm ok, but my comment was addressed to the analysis Maxime did in https://github.com/smartcoop/smart-cfa/pull/240#issuecomment-1168334755 😅

2022-07-04 14:25 UTC, Victor-van-Duijnen commented on src/Shared/Smart.FA.Catalog.Shared/Helper/Guard.cs
> +    public static string? AgainstMaxHtmlInnerTextLength(string? htmlInput, int maxValue, [CallerArgumentExpression("htmlInput")] string paramName = null, string? message = null)
Not fan of putting the HTMLAgilityPack inside the shared application because now showcase has a depency to a package that is completely useless for it. Was it not possible to pass the inner html text to the AgainstMaxLength instead of having a custom guard clause for it?

2022-07-04 14:25 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Attributes/SanitizedAttribute.cs
> +/// Specifies that a property should be sanitized.
"Should be" or "will be" sanitized?

2022-07-04 14:25 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Attributes/SanitizedAttribute.cs
> +[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
The AllowMultiple option is the default apparently, so it can be removed.

2022-07-04 15:05 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Attributes/SanitizedAttribute.cs
> +/// Specifies that a property should be sanitized.
Without a "able" suffix it does not make any sense to have "should".
Btw [Sanitizable] was my first go.

If [Sanitize] is kept.

> Specifies that a property is to be sanitized

is that correct in english ? 
@LievenPraet  inputs ?

2022-07-04 15:08 UTC, maxime-poulain commented
@Victor-van-Duijnen 
@LievenPraet 

We will most likely not merge this PR because we are facing too many issues with Design System's CSS that interfere will basic HTML.

Example 

> <ul> <li> </li> </ul> 

are not rendered and many more visual issue.
There's workaround tho like manipulating the output to add accordingly correct classes but I guess it starts to be way to many workarounds.

I suggest to have a chat with Joelle tho to see what's her opinion.
The backend part can be merged or the PR can just be closed and later on you can see what to do about it.

2022-07-20 16:06 UTC, merged