SuperUser page for denying access to a trainer
smartcoop/smart-cfa pull request #241
Opened 2022-06-28 11:10 UTC by Victor-van-Duijnen

This PR introduces a super user page and a set of method to list trainers and deny them access as well as remove all their data from the database. 
As always the wording used are up for discussion (I know for example inclusive wording would replace blacklist by denylist or rejectlist or blocklist but I chose to take the traditional route to avoid confusion).

2022-06-28 13:46 UTC, maxime-poulain commented
I feel like most (or all?) VC are overkill for their uses and could be replaced with partial view.
The VC we already have (AdminTrainingTile) make sense because it has a bit of logic (even tho it is more or less not used).

2022-06-28 13:49 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetOtherTrainersListQuery.cs
> +        if (!request.TrainerName.IsNullOrEmpty())
You should not be using this, it's meant to be used on collections:
![image](https://user-images.githubusercontent.com/90202188/176195314-e99edf91-fdfb-48c7-bd24-adf3cbdb8812.png)

2022-06-28 13:56 UTC, Victor-van-Duijnen commented on src/Shared/Smart.FA.Catalog.Shared/Collections/PagedList.cs
> +public static class PagedListExtensions
Yes actually that class even existed already moved it just before your comment XD

2022-06-28 13:58 UTC, maxime-poulain commented on src/Shared/Smart.FA.Catalog.Shared/Collections/PagedList.cs
> +public static class PagedListExtensions
But I feel it is not necessary to have that (as far I understood it is used for the tile pagination view ?)

We should merge the pagination component once and for all. You can even try it out quickly in like 15 minutes it's done (I can also give you my linqpad script to populate hundreds of trainings).

You can also introduce some interface that exposes the properties you wanted access to

2022-06-28 14:29 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml
> +            @await Component.InvokeAsync(nameof(Shared.Components.PagingTile.PagingTile), new { list = Model.TrainerList.ToPagedListOfObjects(), route = Routes.SuperUserTrainerList })
I don't really see the point to have a view component named differently from the class of the view component. Following the doc, they are advising against using hardcoded string https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-6.0#avoid-hard-coded-strings

2022-06-28 14:29 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetOtherTrainersListQuery.cs
> +        if (!request.TrainerName.IsNullOrEmpty())
Yes good catch, went too fast on that one.

2022-06-28 14:37 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml
> +            @await Component.InvokeAsync(nameof(Shared.Components.PagingTile.PagingTile), new { list = Model.TrainerList.ToPagedListOfObjects(), route = Routes.SuperUserTrainerList })
In general it is a bad idea to hard code string instead of using constants.
you could for example have a ViewComponents class that holds all the nameof(xxxx) where xxx are the VC classes.
For example, none of the tag helper uses hardcoded string but constants (well they are hardcoded).

Regarding the VC:

![image](https://user-images.githubusercontent.com/90202188/176205193-6ee75707-b0b6-43f3-9bb1-6b28da8f4d13.png)
![image](https://user-images.githubusercontent.com/90202188/176205270-19d2cf88-3e6e-49f8-86eb-508469d7c464.png)

That comment about avoiding hardcoded string is because you may rename your class name and then you got fucked.

![image](https://user-images.githubusercontent.com/90202188/176205452-e2842833-d034-4c8a-9c1c-ba422ea59e64.png)

What's the behavior with rider ?

2022-06-28 14:48 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml
> +            @await Component.InvokeAsync(nameof(Shared.Components.PagingTile.PagingTile), new { list = Model.TrainerList.ToPagedListOfObjects(), route = Routes.SuperUserTrainerList })
That's the trade off between the two choices. The compilation doesn't break so if you rename you might have some kind of surprises

2022-06-29 09:11 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/SuperUserTrainerListTile/SuperUserTrainerListTile.cs
> +    public Dictionary<string, string> SocialNetwork { get; set; } = new();
You could pluralize this property.

2022-06-29 09:11 UTC, LievenPraet requested changes

2022-06-29 09:11 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/SuperUserTrainerListTile/Default.cshtml
> +                    <button class="c-button c-button--borderless c-button--icon" type="button" data-trainerId="@Model.Id" data-dialog="delete-trainer-dialog-confirmation" onclick="setTrainerId(@Model
We need a confirm smart button that could be used here in the future.
You agree, @maxime-poulain ?

2022-06-29 09:11 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml.cs
> +        return RedirectToPage();
It seems more logical to handle the error case first and put the success case last.

2022-06-29 09:20 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/DeleteTrainerCommand.cs
> +        _catalogContext.Remove(trainer);
A golden rule (to me at least) should be that

> any commands (i.e. something that will change the state of your system) should(must?) come with a validator associated with it.

That way it makes it easier to build a more resilient system.

I think it is pretty straight forward (at least for non complex scenerios): 

- "I need to delete some trainer";
- "Ok writing the validation what do I need to be true in order to process ? "
- "The trainer must exist"

Then you add a rule that ensures the id you provided does exist.

Of course nothing prevents you to add on top of that some exceptions or debug assertions in your BL / handlers.

Note that if the validation logic is present the framework will handle for you the end user feedback.

Second note, it is easy to consider having an exception being thrown if there are no validator associated to a command.
(Well one could add a validator that just do nothing but it could be a guard to be considered).

2022-06-29 13:54 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/DeleteTrainerCommand.cs
> +        _catalogContext.Remove(trainer);
That's why it becomes interesting with using EF, instead of making a call (Any()) to see if an entity does exist you can just issue the retrieval and it will be cached.
So later on the same object will be resolved instead of hitting the database again.

Performance wise even if you would be doing some select 1 to make sure something exist it would not matter that much in the end.

2022-07-04 10:24 UTC, maxime-poulain requested changes

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Handlers/UserAdminAuthorizationResultHandler.cs
> +                context.Response.StatusCode = StatusCodes.Status403Forbidden;
If it possible the StatusCode is already that value ?

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/MustNotBeBlackListed.cs
> +/// Requires that the user was not blacklisted.
```suggestion
/// Requires that the user is not blacklisted.
```

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +        conventions.AuthorizeFolder("/SuperUser", Policies.MustNotBeBlackListed);
Should we be able to black list a super user ?
I guess by default a user that can be blacklisted should be able to access the super user space ?

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/SuperUserTrainerListTile/SuperUserTrainerListTile.cs
> +        var isTrainerBlackListed = await IsBlackListed(trainer);
```suggestion
        var isTrainerBlackListed = await IsBlackListedAsync(trainer);
```

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/SuperUserTrainerListTile/SuperUserTrainerListTile.cs
> +    public async Task<bool> IsBlackListed(Trainer trainer) => await _mediator.Send(new IsTrainerBlackListedRequest { TrainerId = trainer.Id });
```suggestion
    public async Task<bool> IsBlackListedAsync(Trainer trainer) => await _mediator.Send(new IsTrainerBlackListedRequest { TrainerId = trainer.Id });
```

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml.cs
> +    public IMediator Mediator { get; }
Do you need those two properties to be public ?

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml.cs
> +        // Get All trainers (except yourself) paged
Yourself would refer to the reader of the code I guess :p

```suggestion
        // Get All trainers (except current connected user) paged
```

or

```suggestion
        // Get All trainers (but current connected user) paged
```

or keep it that way.

2022-07-04 10:24 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainers/SuperUserTrainerList.cshtml.cs
> +        TrainerList = await Mediator.Send(getTrainerListRequest);
Having the code a bit formatted would be better.

2022-07-04 10:52 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerQuery.cs
> +public class GetTrainerRequest : IRequest<GetTrainerResponse>
`ById` is preferable

2022-07-04 11:01 UTC, LievenPraet requested changes

2022-07-04 12:44 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/ContextModelSnapshot.cs
> +                        .HasMaxLength(200)
Yes indeed, some weird swapping happened. I have corrected that.

2022-07-04 12:48 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Handlers/UserAdminAuthorizationResultHandler.cs
> +                context.Response.StatusCode = StatusCodes.Status403Forbidden;
Yes but in that case, I would rather be explicit about what to expect in that kind of failure.

2022-07-04 12:48 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +        conventions.AuthorizeFolder("/SuperUser", Policies.MustNotBeBlackListed);
I have asked business, I will come back to that one.

2022-07-04 13:09 UTC, maxime-poulain requested changes

2022-07-04 13:31 UTC, LievenPraet commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/403.cshtml.cs
> +        }
Same remark here. Code would be cleaner with returns instead of if/else...

2022-07-04 13:44 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
> +        conventions.AuthorizeFolder("/SuperUser", Policies.MustNotBeBlackListed);
I have confirmation from @Geraldineb1  that a super user could be blacklisted.

2022-07-04 14:37 UTC, LievenPraet approved these changes

2022-07-04 15:41 UTC, maxime-poulain approved these changes
Left one optional minor comment

2022-07-04 15:41 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetOtherTrainersListQuery.cs
> +public class GetOtherTrainersListRequest : IRequest<PagedList<Trainer>>
Not requesting a change just a suggestion, so as you prefer:

> GetTrainersByNameOrEmailExceptSelf ?

2022-07-04 15:41 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetOtherTrainersListQuery.cs
> +        var trainerQueryable = _catalogContext.Trainers
Since we have no validator would be wise to check if the self trainer id is not equal to default ?

2022-07-04 16:15 UTC, merged