[ShowCase] add an avatar and a link to conatct form on trainingdetails page
smartcoop/smart-cfa pull request #248
Opened 2022-07-06 08:45 UTC by ChMelissa

# ShowCase

Add an avatar and a link to conatct form on trainingdetails page

https://smartjira.atlassian.net/browse/CFA-481

2022-07-06 10:46 UTC, Victor-van-Duijnen reviewed
Nice one! Don't have much to say. 
Outside of the scope of this PR but I have noticed in the cs of the page **TrainingDetails**, line 57,
we might want to change the code to that:
`  (...)  var firstTrainerDetail = trainingDetails.First();
        return new TrainingDetailsViewModel
        {
            Id = firstTrainerDetail.Id,
            TrainingTitle = firstTrainerDetail.TrainingTitle,
            Goal = firstTrainerDetail.Goal ?? string.Empty,
            Methodology = firstTrainerDetail.Methodology ?? string.Empty,
            PracticalModalities = firstTrainerDetail.PracticalModalities ?? string.Empty,
(...)`
since we are at it :)

2022-07-06 10:46 UTC, Victor-van-Duijnen commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        _minIoSettings = minIOSettings.Value ?? throw new InvalidOperationException($"MinIO options not defined");
```suggestion
        _minIoSettings = minIOSettings.Value ?? throw new InvalidOperationException("MinIO options not defined");
```
or 

```suggestion
        _minIoSettings = minIOSettings.Value ?? throw new InvalidOperationException($"{nameof(minIOSettings)} not defined");
```

2022-07-06 12:48 UTC, maxime-poulain requested changes

2022-07-06 12:48 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Smart.FA.Catalog.Showcase.Domain.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.6" />
You can remove this NuGet it is added by default by EF Core Power Tools.

2022-07-06 12:48 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220705103901_AddProfilImage.cs
> +               ALTER VIEW [Cfa].[v_TrainingDetails]
Could you keep the existing formatting:
```sql
                SELECT training.Id
                    ,details.Title
                    ,details.Methodology
                    ,details.Goal
                    ,details.PracticalModalities
                    ,topic.TopicId
                    ,details.Language
                    ,trainer.FirstName
                    ,trainer.LastName
                    ,trainer.Id AS TrainerId
                    ,trainer.Title AS trainerTitle
                    ,training.TrainingStatusTypeId
                FROM [Cfa].[Training] AS training
                    INNER JOIN [Cfa].[TrainingLocalizedDetails] AS details
                    ON training.Id = details.TrainingId
                    INNER JOIN [Cfa].[TrainerAssignment] trainingTrainer
                    ON training.Id = trainingTrainer.TrainingId
                    INNER JOIN [Cfa].[Trainer] trainer
                    ON trainingTrainer.TrainerId = trainer.Id
                    INNER JOIN [Cfa].[TrainingTopic] topic
                    ON training.Id = topic.TrainingId
                    INNER JOIN Cfa.TrainingStatusType trainingStatusType
                    ON trainingStatusType.Id = training.TrainingStatusTypeId
                WHERE TrainingStatusType.Name = 'Published'
```

I assume you just added the column profile ?

2022-07-06 12:48 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Migrations/20220705103901_AddProfilImage.cs
> +            migrationBuilder.Sql(@"
same about formatting

2022-07-06 12:48 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +<div class="c-dialog-context o-flex--center" id="inquiry-form-dialog">
Could you make a partial view ? Its code duplicate with the contact popup in the trainer details and if any change happens it will be maintaining stuff at two places.

2022-07-06 12:48 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +    public TrainingDetailsModel(Infrastructure.Data.CatalogShowcaseContext context, IOptions<MinIOOptions> minIOSettings, ITrainerInquirySendEmailService trainerInquirySendEmailService)
Remove the

> Infrastructure.Data

2022-07-06 12:48 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        Training = MapTrainingDetails(trainingDetails);
You could move the logic that makes the mapping and a plus would be to move the logic to retrieve the ViewModels inside the TrainingService (you can skip adding DAL logic in some extensions method).

2022-07-08 08:32 UTC, Victor-van-Duijnen approved these changes

2022-07-08 08:32 UTC, Victor-van-Duijnen commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Smart.FA.Catalog.Showcase.Domain.csproj
> +
```suggestion
```

2022-07-08 09:05 UTC, maxime-poulain approved these changes

2022-07-11 08:07 UTC, merged