Feature/refactoring
smartcoop/smart-cfa pull request #31
Opened 2022-03-21 14:40 UTC by Victor-van-Duijnen

I introduce some small refactoring. 
Since they are very small, instead of spamming you with 3 different PR's, I have madeonly  one PR with 3 small commits.
The PR includes:

1. Refactor the switch statements out from the event dispatcher and use the mediator pattern to send domain events(caught by a notification handler).
2. Replace hard dependencies in the constructor of the catalog context with an injected option pattern
3. Renaming of the method injecting a catalog context in the integration tests

2022-03-21 16:53 UTC, LievenPraet requested changes

2022-03-21 16:53 UTC, LievenPraet commented on Smart.FA.Catalog.IntegrationTests/TrainingContext/User_Tests.cs
> +        var user = await handler.Handle(request, CancellationToken.None);
Var should be named `trainer` 
```suggestion
        var trainer = await handler.Handle(request, CancellationToken.None);
```

2022-03-21 16:53 UTC, LievenPraet commented on Smart.FA.Catalog.IntegrationTests/TrainingContext/User_Tests.cs
> +    public async Task CanGet()
We are calling `GetTrainerFromUserAppRequest` but the function name is `CanGet`.
The name of this function is not clear and doesn't give enough / correct details of what we are testing.

2022-03-21 16:53 UTC, LievenPraet commented on src/Smart.FA.Catalog.Application/UseCases/DomainEventHandlers/ValidateTrainingDomainEventHandler.cs
> +            notification.TrainingName, notification.TrainersId);
Will an exception be thrown if the validation fails?

2022-03-21 16:53 UTC, LievenPraet commented on src/Smart.FA.Catalog.Infrastructure/DesignTimeContextFactory.cs
> +            $"\nDesignTimeContextFactory.Create(string[]):\n\tBase Path: {basePath}\n\tEnvironmentVariable: {environmentName}");
Could we use a logger here instead of console writeline?

2022-03-22 08:08 UTC, Victor-van-Duijnen commented on Smart.FA.Catalog.IntegrationTests/TrainingContext/User_Tests.cs
> +        var user = await handler.Handle(request, CancellationToken.None);
Yes good point

2022-03-22 08:16 UTC, Victor-van-Duijnen commented on src/Smart.FA.Catalog.Infrastructure/DesignTimeContextFactory.cs
> +            $"\nDesignTimeContextFactory.Create(string[]):\n\tBase Path: {basePath}\n\tEnvironmentVariable: {environmentName}");
The DesignTimeContextFactory is only used when you want to recreate the state of the DB from ef tools commands inside the project (in isolation of the solution) so actually no debugging need to/should be done in that part (the console message is purely informative about the progress of the designtimecontextfactory). It is NEVER used at runtime : https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-a-design-time-factory

2022-03-22 08:22 UTC, Victor-van-Duijnen commented on Smart.FA.Catalog.IntegrationTests/TrainingContext/User_Tests.cs
> +    public async Task CanGet()
Yes I can see how that can be confusing, I will change it. Right now my naming convention would have been 'CanGetFromTrainer' (the scope of the tests is defined by the name of the class, here User_Tests, so all operations are definitively made on the User). The 'Can' part of the message indicates that all input of the test should be valid (to differentiate 'CantGet' tests when we have invalid input). But I will standardize my naming of tests to yours (starting by that one)!

2022-03-22 08:29 UTC, Victor-van-Duijnen commented on src/Smart.FA.Catalog.Application/UseCases/DomainEventHandlers/ValidateTrainingDomainEventHandler.cs
> +            notification.TrainingName, notification.TrainersId);
That method is not validating anything, it's just propagating the domain event (the validating event itself is done before and the exception handling, too). If the validating fails, it will indeed throw a "Validating error" and will never arrives in the method described here.  That method here is just supposed to log some message right now and that's why there is no exception handling.

2022-03-22 10:20 UTC, maxime-poulain commented on src/Smart.FA.Catalog.Application/UseCases/DomainEventHandlers/ValidateTrainingDomainEventHandler.cs
> +            notification.TrainingName, notification.TrainersId);
Regardless you go for event driven architecture or not, publishing events should be restricted to strong state changes. Namely creation, edition, stuff like that.
You might prefer to have something that surrounds every validation and do something upon validating rather than using an event.

2022-03-22 10:33 UTC, Victor-van-Duijnen commented on src/Smart.FA.Catalog.Application/UseCases/DomainEventHandlers/ValidateTrainingDomainEventHandler.cs
> +            notification.TrainingName, notification.TrainersId);
No, your a confusing what I do in that validation. That validation is for switching a training from status "In Review" or "In Draft" to a status Published, not to validate if the model is valid. So it's a very important state change that definitively needs to be published as an event.

2022-03-22 10:57 UTC, maxime-poulain commented on src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            {
I guess you can neste the loggerFactory create inside this ef.
Wouldn't it be better to set the log level through the app settings rather than hardcoded that here ?
`    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }`

2022-03-22 10:57 UTC, maxime-poulain commented on src/Smart.FA.Catalog.Web/appsettings.Development.json
> +  {
Hm I think you can remove the Options suffix. "Logging" section is also behind the scene an option for example;
Would it  make sense to name it also name it someting like EfCore as this settings is strongly related to that technology ?

2022-03-22 16:52 UTC, Victor-van-Duijnen commented on src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            {
Standard logs in the application should be separated from raw queries (useconsolelogger) only used for very specific debugging purpose. They should only be used in particular scenario where it would give important tracing information, but never for a long period time since they are VERY VERY verbose (even more than the trace log level) obviously. It already depends on the appsettings and it's therefore not hardcoded (but I guess you meant the fact that it is a cutsom field rather than the customary log settings). I suggest we keep it separated from the standard logs.

2022-03-22 16:53 UTC, Victor-van-Duijnen commented on src/Smart.FA.Catalog.Web/appsettings.Development.json
> +  {
Ok I can do that, II have tended to use the "Options" postfix for all information but maybe it's a bit redundant indeed. I will change it.

2022-03-22 16:54 UTC, Victor-van-Duijnen commented on Smart.FA.Catalog.IntegrationTests/Base/ConnectionSetup.cs
> +            InitialCatalog = "Catalog",
It's true we have decided to go for a more simple, straightforward name for our DBs but we are open to suggestions!

2022-03-22 17:09 UTC, maxime-poulain commented on src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            {
Well, what I meant, was "is it possible to filter the console logs with a appsettings:" ?
 let's say you add this in your appsetting:
`{
"LogLevel": { "Microsoft.EntityFrameworkCore.Database.Command": "Trace"
}`

than commands won't be written however the reste will remains at the information level.
The idea was to know if we can setting up, in the same way I described above.
The idea is that locally let's say I want to have some output in the console but not the command, is it possible ? 
Writing logs to a file is way to retarded,I was not suggesting that :p. There would be too many I/O.

>I guess you can neste the loggerFactory create inside this ~~ef~~ **if**, sorry.

2022-03-29 16:12 UTC, merged