Fix broken paging in training listing page
smartcoop/smart-cfa pull request #60
Opened 2022-04-05 13:28 UTC by Victor-van-Duijnen

The Introduction of topic ids (also called categories or tags) had broken the paging system of the list of trainings.
The PR maps topic ids to a list in Training dto with the multi-mapping feature of dapper to fix the paging.

2022-04-06 18:19 UTC, maxime-poulain requested changes

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Dto/TrainingDto.cs
> +    public TrainingDto(int trainingId,
Missing break line.

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Dto/TrainingDto.cs
> +    }
```suggestion
        this.TrainingId = trainingId;
        this.StatusId = statusId;
        this.Title = title;
        this.Goal = goal;
        this.Language = Language;
        this.TopicIds = new List<int>();
```
```suggestion
        TrainingId = trainingId;
        StatusId = statusId;
        Title = title;
        Goal = goal;
        Language = Language;
        TopicIds = new List<int>();
```

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Dto/TrainingDto.cs
> +    }
```suggestion
        this.TrainingId = trainingId;
        this.StatusId = statusId;
        this.Title = title;
        this.Goal = goal;
        this.Language = Language;
        this.TopicIds = new List<int>();
```
```suggestion
        TrainingId = trainingId;
        StatusId = statusId;
        Title = title;
        Goal = goal;
        Language = Language;
        TopicIds = new List<int>();
```

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Read/TrainingQueries.cs
> +    //TODO: it's a bit heavy for a simple paging system (though it works), we might want to look to refactor that at some point
50 lines just to get a simple paginated list seems to be a bit overkill, why not refactor that in the same time ?  :).

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Read/TrainingQueries.cs
> +    //TODO: it's a bit heavy for a simple paging system (though it works), we might want to look to refactor that at some point
50 lines just to get a simple paginated list seems to be a bit overkill, why not refactor that in the same time ?  :).

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
> +            <smart-muted-text text="@string.Join(", ", _localizer[Enumeration.FromValue<TrainingTopic>(tag).Name])"></smart-muted-text>
The string.join is not necessary as the argument is just a string but the figma layout uses a comma seperation:

![image](https://user-images.githubusercontent.com/90202188/162041897-2cec8b56-7775-4140-9d9b-a64d34229ead.png)
![image](https://user-images.githubusercontent.com/90202188/162041897-2cec8b56-7775-4140-9d9b-a64d34229ead.png)
![image](https://user-images.githubusercontent.com/90202188/162041897-2cec8b56-7775-4140-9d9b-a64d34229ead.png)

2022-04-06 18:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
> +            <smart-muted-text text="@string.Join(", ", _localizer[Enumeration.FromValue<TrainingTopic>(tag).Name])"></smart-muted-text>
The string.join is not necessary as the argument is just a string but the figma layout uses a comma seperation:

![image](https://user-images.githubusercontent.com/90202188/162041897-2cec8b56-7775-4140-9d9b-a64d34229ead.png)
![image](https://user-images.githubusercontent.com/90202188/162041897-2cec8b56-7775-4140-9d9b-a64d34229ead.png)
![image](https://user-images.githubusercontent.com/90202188/162041897-2cec8b56-7775-4140-9d9b-a64d34229ead.png)

2022-04-07 07:00 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Read/TrainingQueries.cs
> +    //TODO: it's a bit heavy for a simple paging system (though it works), we might want to look to refactor that at some point
A bit too big for an improvised ticket in my sprint, I have put the refactor in my backlog but it needs changing the whole class. I still needed to fix that ASAP because it's kind of blocking.

2022-04-07 07:52 UTC, CelineMarique approved these changes

2022-04-08 13:59 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Dto/TrainingDto.cs
> +public class TrainingDto
Putting a space after yours slashes 
ie.e
// Hello I am maxime.
Is more common and recommended.
I was surprised that Microsoft even asks for it.
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#commenting-conventions

2022-04-12 14:11 UTC, merged