Add practical modalities field to training
smartcoop/smart-cfa pull request #63
Opened 2022-04-06 14:36 UTC by Victor-van-Duijnen

1. Create a new field in the training model for the practical modalities with:

- Testing
- Validation
- Migration

2. Revise Precision in validators and domain layer of the training fields

- min and max length of Title, Methodology, Goal, PracticalModalities

2022-04-06 18:08 UTC, maxime-poulain requested changes

2022-04-06 18:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Validators/TrainingDetailValidation.cs
> +            .NotEmptyWithGenericMessage().WithMessage(Errors.General.MissingField("practicalModalities").Message);
Why not use the resources here ?
I assume those validation messages are used somehow ?

2022-04-06 18:08 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
> +  </data>
You use in the above code 1500 for the max length.

2022-04-06 18:10 UTC, maxime-poulain commented
Hello,
While reviewing this I noticed that the validators of Models class  name is different than the file name but I cant write a comment sadly in the code :(
https://github.com/smartcoop/smart-cfa/blob/7247a632c399bdec6696bce660c8184b917b6b1f/src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs

2022-04-07 07:55 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
> +            .MaximumLength(1000)
Well, yes, I did'nt want to introduce that in that PR because it needs change on whole the fields of the object (it's in my next PR). When you defined the min Lenght and max length in validator without changing the business logic, it was already wrong but I have only noticed it when adding the field.

2022-04-07 07:59 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
> +  </data>
No, not in the validator of the pages. I intend to create a PR with the right field size for multiple fields in the database that were not in phase with what was added in the validators but it's outside the scope of that PR.

2022-04-07 08:06 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Validators/TrainingDetailValidation.cs
> +            .NotEmptyWithGenericMessage().WithMessage(Errors.General.MissingField("practicalModalities").Message);
This the validation used in the Domain layer. It's not meant to be displayed but logged so It should not be localized.

2022-04-07 08:10 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/TrainingDetail.cs
> +                    string.IsNullOrEmpty(fieldValue) || fieldValue.Length < maxValue,
The initial idea was to use expressions to create lots of dynamic filters with EF (not possible with Action) but I don't think I will go that road anyway, so I will refactor that.

2022-04-07 16:38 UTC, Victor-van-Duijnen commented
Following @maxime-poulain 's comments I have extended the scope of the PR to include revision of the precision (min/max length) of the training fields (Title, Goal, Methodology and PracticalModalities).

2022-04-08 08:30 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Validators/TrainingDetailValidator.cs
> +public class TrainingDetailValidator: AbstractValidator<TrainingDetail>
```suggestion
public class TrainingDetailValidator : AbstractValidator<TrainingDetail>
```

2022-04-08 08:30 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/SeedWork/Guard.cs
> +    public static void AgainstMinStringLength(string value, string valueName, int minValue, string? message = null)
missing breakline

2022-04-08 08:30 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Core/SeedWork/Guard.cs
> +    public static void AgainstMaxStringLength(string value, string valueName, int maxValue, string? message = null)
Donc include "String" in your method name it can be inferred easily thanks to the value parameter.

Later on there will be most likely another method on collection's maximum, we dont need to have something called
>AgainstMaxCollectionLength

I would rename valueName to "parameterName" or "argumentName" as it refers to the calling parameter.
maxValue to maximumLength to make it less vague.

Regarding the method name I think AgainstMaximumLength makes more sense than AgainstMaxLength

2022-04-08 08:30 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
I did not put any error message because we have already on the helper text telling us the min / max length information.
I think that having twice the same message is not really user friendly.

2022-04-08 08:30 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
> +            RuleFor(viewModel => viewModel.Methodology)
FluentValidation's length valiator doesn't care if the value if null.
See
https://github.com/FluentValidation/FluentValidation/blob/2671e7fb09af9e1ef2a938a8b4364724ef9e47bd/src/FluentValidation/Validators/LengthValidator.cs#L47

2022-04-08 08:49 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
> +            RuleFor(viewModel => viewModel.Methodology)
Nice spotting! I will remove the redundant where clause.

2022-04-08 08:50 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
Hmm not totally agree, you might not automatically know if you have reached 30 characters, so you have to know with a error text that the field is not valid and need changes.

2022-04-08 13:53 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
Thinking of it again yeah should be better to have an error message even if e have an helper text.

However, why did you remove the max length on the validator when publishing ?
Isn't there a limit expected ? I know we do at a database constraint at least.

2022-04-11 08:59 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
No no maxLength is applied but since  the part commented, is limited to published training and that the limit of character should be applied to both draft and published training, I have moved that logic up (if you look at the start if the validator you can see that there is length max validation happening there)

2022-04-12 14:11 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingDetailConfigurations.cs
> +            .HasMaxLength(1000)
I think the guard clause + db constraint is 1500

2022-04-12 14:23 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/Configuration/TrainingDetailConfigurations.cs
> +            .HasMaxLength(1000)
Hmm nop everything is 1000 (Guard + DB + Validator) but I agree I had some doubts about it when I first read your comment :b

2022-04-12 15:35 UTC, maxime-poulain approved these changes

2022-04-12 15:40 UTC, merged