Fix/cfa 322 fix broken js
smartcoop/smart-cfa pull request #66
Opened 2022-04-07 16:35 UTC by maxime-poulain

There was  a onload event logic applied globally to every pages but that logic is related only to creation and edition pages.
Therefore opening any pages but those two would result in this:
'Cannot read properties of null (reading 'addEventListener')'.
This PR provides a quick and dirty fix by returning in nothing is found.

Internal ticket:
https://smartjira.atlassian.net/browse/CFA-322

2022-04-11 09:26 UTC, Victor-van-Duijnen requested changes

2022-04-11 09:26 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +    // This is used only by the creation and edition page therefore it could be move somewhere else.
```suggestion
    // This is used only by the creation and edition page therefore it could be move somewhere else.
```
```suggestion
    // This is used only by the creation and edition page therefore it could be moved somewhere else.
```

2022-04-11 09:26 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +    // Btw try avoiding jQuery please :(.
Let's try to avoid recommending guidelines directly in code comments. It could be discussed over informally together or more officially in a rulebook that we would create :)

2022-04-11 09:26 UTC, Victor-van-Duijnen commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +    // Btw try avoiding jQuery please :(.
Let's try to avoid recommending guidelines directly in code comments. It could be discussed over informally together or more officially in a rulebook that we would create :)

2022-04-11 09:26 UTC, Victor-van-Duijnen commented
Nice initiative!

2022-04-12 14:19 UTC, maxime-poulain commented on src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
> +    // This is used only by the creation and edition page therefore it could be move somewhere else.
Ty

2022-04-14 09:03 UTC, Victor-van-Duijnen approved these changes

2022-04-14 10:14 UTC, merged