Feature/cfa 269 add all trainings page
smartcoop/smart-cfa pull request #67
Opened 2022-04-08 13:16 UTC by CelineMarique

Showcase > Add razor page for all trainings display

https://smartjira.atlassian.net/browse/CFA-269

Adapt DbContext to query training view

    Adapt v_TrainingList to get training status and topic id instead of name.
    Add keys to DbContext and connection settings in DbContext and Program.cs

Add TrainingList page

    Add specific folder for trainings and create Traininglist page.

Add basic template for trainings list
Get sorted training list

    Add a training view model.
    Adapt page controller and html to get only validated trainings and display training topic id (the idea is to have a translation for the topic name at some point).

2022-04-08 13:41 UTC, maxime-poulain requested changes

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/DesignTimeContextFactory.cs
> +{
hm did the tool generate that for you ?

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.Training.TrainingListModel
I would move the cshtml file and its viewmodel into a seperated folder but if you do so, you need to specify the route like

@page "training/list" or something similar.

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml.cs
> +        TrainingList = TrainingList.OrderBy(o => o.TrainingId).ToList();
You could make TrainingList a local variable and remove therefore the public property.
Also i would filter on the IQueryable the status that way to do only one call to ToList

```
var trainingList = _context.TrainingList.Where(training => training.TrainingStatus == TrainingStatus.Validated.Id).ToListAsync();
```

you could also remove the order by  linq extension method ?

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml.cs
> +        {
This seems to me a bit complicated, that 
that should work also
```
        var groupedTrainingByIds = trainingList.ToLookup(t => t.TrainingId);
        var toto = groupedTrainingByIds.Select(trainings =>
        {
            // Since the source is a view, every items of the list has the same training properties.
            var training = trainings.First();
            return new Training()
            {
                TrainerFirstName = training.TrainerFirstName,
                TrainerLastName  = training.TrainerLastName,
                TrainingId       = training.TrainingId,
                TrainingStatus   = TrainingStatus.Validated,
                TrainingTitle    = training.TrainingTitle,
                Topics           = training.Select(x => TrainingTopic.FromValue<TrainingTopic>(x.TrainingTopic)).ToList()
            };
        });
 ```

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Program.cs
> +
This can be remove, it allows you to inject throught IHttpontextAccessor interface the current http context but in our case it wont be used, or at least i think.

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Program.cs
> +{
This works also

```suggestion
builder.Services.AddDbContext<CatalogShowcaseContext>(efOptions)
```

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/Training.cs
> +public class Training
Some people like to append "viewModel" at the end of classes that are exposing informations to your page/view.

I think it could make more sense to have it as the class is not in some "ViewModel" folder but honestly up to you.

2022-04-08 13:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/efpt.config.json
> -{
We got EF power tools config files now both in the infra & the domain projects.
We should just stick with one config.

Feel free to decide whether the config files should be in the domain or infra project.
Usually I put that in the Domain project but it is just a personal preference

2022-04-08 13:44 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/Training.cs
> +    public List<string> TrainingLanguages { get; set; } = new List<string>();
I think you can safely remove that property, it is not an information we need to expose to the end user.

2022-04-11 07:24 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.Training.TrainingListModel
They're already in a _Training_ folder inside of Pages
Do you mean you would separate the view model and the cshtml in different folders?

2022-04-11 07:26 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/DesignTimeContextFactory.cs
> +{
No

2022-04-11 07:28 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/Training.cs
> +public class Training
Ok, we can all decide to append view models like that

2022-04-11 07:45 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/Training.cs
> +    public List<string> TrainingLanguages { get; set; } = new List<string>();
In this context, but a training view model can be shared with a TrainingDetails page, it is the same model, and we do want to know the language of the training

2022-04-12 13:07 UTC, maxime-poulain requested changes

2022-04-12 14:19 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +                            <a class="training-list__category-link" asp-page="TrainingViewModel/TrainingViewModelList" asp-route-cat="TopicName">@topic.Id</a>
it's going to be `asp-route-id=@training.TrainingId`

2022-04-13 07:34 UTC, Victor-van-Duijnen commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.Training.TrainingListModel
@CelineMarique  It's really a matter of preference, but if we want to have more coherence between showcase and useradmin, I guess it would be better to have a folder per view where there would be your view model mappping logic (anyway we never know what next page we will need to be there in future releases). 

Although, you could still use the same view model between the pages!
We chose to go for separation of the view models for each view to avoid having one single "monolith" view model mapped for each view, but the same logic does not necessary apply to showcase since the data to be displayed is quiet different.

2022-04-13 08:02 UTC, LievenPraet requested changes

2022-04-13 08:02 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml.cs
> +                TrainingTitle = groupedTraining.First().TrainingTitle,
If `groupedTraining` is empty, calling `First` will cause a crash.
Use `FirstOrDefault` instead and use the `?` operator.
Same remark for other instances where you use `First`.
```suggestion
                TrainingTitle = groupedTraining.FirstOrDefault()?.TrainingTitle,
```

2022-04-13 08:25 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml.cs
> +                TrainingTitle = groupedTraining.First().TrainingTitle,
We do not call .First() at any time.

2022-04-13 08:27 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml.cs
> +                TrainingTitle = groupedTraining.First().TrainingTitle,
We do not call .First() at any time for a training, We do it for the training status. Normally, there should be no trainings encoded without status. I can change it for .FirstOrDefault()

2022-04-13 10:38 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +                            <a class="training-list__category-link" asp-page="TrainingViewModel/TrainingViewModelList" asp-route-cat="TopicName">@topic.Id</a>
This is a hyperlink under a topic isn't it ? Shouldn't click on a link, let's say "marking", open all marketing trainings ?

2022-04-13 10:41 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml.cs
> +                TrainingTitle = groupedTraining.First().TrainingTitle,
Nah at that point we now for a fact we have at least one record.
We grouped by the training id just before.

2022-04-13 10:53 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingList.cs
>      public string TrainerLastName { get; set; }
Sadly we cannot anymore.
We went with SQL views.

In the first place, we did not want, unless impossible to do otherwise, sharing the domain layer of the UserAdmin Catalog part with the showcase website.

The UserAdmin domain comes with multiple dependencies that should not be a concern of a "public" website.

Therefore we considered those approaches :

- Making an actual API exposing the data that the showcase website needs.
- Using specific SQL views to scaffold actual DTO's for the showcase website.
- Scaffold database tables and use simple EF Core queries

Since 1) is not possible, we thought going with 2) would have been a good approach.
3) is actually the easiest as you don't depend of anything but still retarded as you got same definitions across two different projects.

2022-04-13 11:14 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.Training.TrainingListModel
>I was planning on sharing the view model with the upcoming TrainingDetails page

Usually you want to avoid re-using viewmodels accross pages, by definition a ViewModel exposes data to a given page.
The data that exposes "TrainingListViewModel" is for a training title training right ?
The ViewModel (or dto w/e) you gonna need for the detail of a training has more more fields such goal, methodology, etc.
The idea is also at some point to refactor the tile into a view component to make it reusable between the home page and the training list page.

However you pointed out something interesting: 
>There is no plan to have more views 'training related'

Why not create a base training view model that has common properties of every pages ?
If you don't want to have multiple files / folders, it is **OK** to have your page's viewmodel inside your XXX.cshtml.cs file.

2022-04-13 11:19 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.Training.TrainingListModel
You can see in the last fixups that i followed your recommendations.

2022-04-13 11:21 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +                            <a class="training-list__category-link" asp-page="TrainingViewModel/TrainingViewModelList" asp-route-cat="TopicName">@topic.Id</a>
I don't know yet the intention for those links. 
@joe-ubik , could you let us know if there will be some kind of page for a topic.
here I just followed the design introduced by Vio.

2022-04-14 09:18 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_Layout.cshtml
> +                        <a class="header-nav__link" asp-area="" asp-page="/Training/TrainingList/TrainingList">Formations</a>
I don't want to use /Trainings. It was the default html inserted by Vio. I'd like to keep the route as it exist in the repository for more clarity. 
Is that a change request?

2022-04-14 12:43 UTC, LievenPraet approved these changes

2022-04-14 17:09 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList.cshtml
> +                            <a class="training-list__category-link" asp-page="TrainingViewModel/TrainingViewModelList" asp-route-cat="TopicName">@topic.Id</a>
Oki, can be adjusted anyway if required later on.

2022-04-14 17:11 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_Layout.cshtml
> +                        <a class="header-nav__link" asp-area="" asp-page="/Training/TrainingList/TrainingList">Formations</a>
Nope it's was not a change request. I just had the feeling "/Training/TrainingList/TrainingList" is a strange route.

2022-04-14 17:13 UTC, maxime-poulain approved these changes

2022-04-15 08:40 UTC, merged