Introduce localization for the showcase project
smartcoop/smart-cfa pull request #74
Opened 2022-04-14 11:53 UTC by maxime-poulain

This PR adds localization support for the showcase public website

2022-04-14 12:09 UTC, CelineMarique requested changes

2022-04-14 12:09 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Extensions/LocalizationRegistration.cs
> +                    // Requirements is to have french has default language.
Requirements are...

2022-04-14 12:09 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Index.cshtml
>      <div class="main-subtitle">Quoi ? Pourquoi ? Comment ?</div>
Are those not being handle in the translation files?

2022-04-14 12:09 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Index.cshtml
>          <h2>Nombre de formations : 122 | Nombre de formateur·trices : 87</h2>
Idem: are they not handle in the translation file?

2022-04-14 12:09 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Rgpd.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.RgpdModel
In my PR I have fixed that issue in a separated commit. 
If your branch get merged first, I would make that change in a specific commit, since it is not linked to the purpose of the work here.

2022-04-14 17:04 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Extensions/LocalizationRegistration.cs
> +                    // Requirements is to have french has default language.
Woopsie thank you.

2022-04-14 17:07 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Index.cshtml
>      <div class="main-subtitle">Quoi ? Pourquoi ? Comment ?</div>
Nope, first exposing the resx files so they can be used by ongoing developments and there is indeed another ticket to migrate hardcoded text into the resx files.

2022-04-14 17:07 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Index.cshtml
>          <h2>Nombre de formations : 122 | Nombre de formateur·trices : 87</h2>
Same than above.

2022-04-14 17:22 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Rgpd.cshtml
> +@model Smart.FA.Catalog.Showcase.Web.Pages.RgpdModel
Yup I noticed that you did that change already in your 269's commits.
I was counting on having your branch merged first x).

2022-04-15 09:26 UTC, CelineMarique approved these changes

2022-04-15 18:16 UTC, merged