Feature/cfa 313 add training details page
smartcoop/smart-cfa pull request #75
Opened 2022-04-14 11:57 UTC by CelineMarique

CFA - Showcase > Add training details page
https://smartjira.atlassian.net/browse/CFA-313

Add SQL view for training detail
    And add script into Infrastructure project.

Add db context and model for training detail
    Add model into Domain project.
    Add context into Infractructure project.
    Adapt DbContext to add keys.

Add training details page
    Add folder and view model.
    Adapt links.
    Map to view model

Proper layout and style will be added in an upcoming branch.

2022-04-14 12:04 UTC, LievenPraet approved these changes

2022-04-14 17:38 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        var trainingDetails = await _context.TrainingDetails.Where(m => m.TrainingId == id).ToListAsync();
You could handle the case where the providen id doesn't exist.
You know let's say i type
/Training/TrainingDetails/TrainingDetail/16554546546545664

You could redirect to a 404 page.
Or simply in the cshtml file write training not found or something.

2022-04-14 17:38 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        training.TrainingGoal = trainingDetails.FirstOrDefault().TrainingGoal;
Like @LievenPraet said in another PR.
You need to use
FirstOrDefault()?.Blabla;

Here the list can be empty and it will result in a null  pointer exception.

However if you handle the case before it's okay.

2022-04-15 08:49 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        var trainingDetails = await _context.TrainingDetails.Where(m => m.TrainingId == id).ToListAsync();
@joe-ubik is it going to be a 404 page or can I use the default Error page that you could customize?

2022-04-21 09:18 UTC, maxime-poulain requested changes
We need to ditch one of the ef core power tools config file either fro the domain or the dal project.

2022-04-21 09:18 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +﻿@page
```suggestion
﻿@page "Training/TrainingDetails/TrainingDetail
```
I think it's a nice to have to have the root "hardcoded"  it helps a bit when you need to create a link to that page.
At better thing would be to have constants, than just strings, but we didn't make it neither in the UserAdmin project.

2022-04-21 09:18 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +            Methodology: @Model.Training.TrainingMethodology
You can localize those strings
"Metholodgy"
There is a nice localization manager that comes with rider and resharper. Can show you how to use if you are not familiar with it.

2022-04-21 09:18 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        var trainingDetails = await _context.TrainingDetails.Where(m => m.TrainingId == id).ToListAsync();
I think we can re-use Smart [Design 404](https://design.smart.coop/development/template-examples/404.html) page like we do in the useradmin.

however, I came with an idea.
Ican add an implementation something like
```csharp
return Notfound(string customMessage);
```
that would allow us to make a custom message in the 404 not found page to have something more user friendly.

2022-04-21 09:18 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml
> +                        <a class="training-list__training-link" asp-page="../TrainingDetails/TrainingDetails" asp-route-id="@training.TrainingId">@training.TrainingTitle</a>
What is the generated html of this ?

2022-04-26 07:35 UTC, CelineMarique commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +        var trainingDetails = await _context.TrainingDetails.Where(m => m.TrainingId == id).ToListAsync();
We can create another ticket after discussion with the team. @joe-coop @joe-ubik

2022-04-26 09:19 UTC, maxime-poulain approved these changes

2022-04-26 09:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_Layout.cshtml
>                          <a class="header-nav__link" asp-area="" asp-page="/Trainers">Formateurs</a>
Routes in the constant is 
```
public const string TrainerList = "/Trainer/TrainerList/TrainerList";
```
This is PR is not about trainer anyway just mentionning it.

2022-04-26 09:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml.cs
> +    private TrainingDetailsViewModel MapTrainingDetails(List<Domain.Models.TrainingDetails> trainingDetails)
```suggestion
    private TrainingDetailsViewModel MapTrainingDetails(List<Domain.Models.TrainingDetails>? trainingDetails)
```
The following can come later but worth mentionning it.
Having the mapping separated in another class is a good practise too.
Well something like this:
https://gist.github.com/maxime-poulain/ff388bb0e888dcc2e35c0b6fee356582

In this case, it is a bit overkill and might be implemented later on.

2022-04-26 09:30 UTC, merged