Feature/cfa 314 add training layouts and css
smartcoop/smart-cfa pull request #82
Opened 2022-04-25 10:27 UTC by NourJammal

CFA
Showcase 
Add training details layouts and css

https://smartjira.atlassian.net/browse/CFA-314

2022-04-25 13:26 UTC, maxime-poulain requested changes

2022-04-25 13:26 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainingDetails.sql
> +trainer.LastName,trainer.Title AS trainerTitle, training.StatusId
For better readability you can apply the following formatting to the select part
![image](https://user-images.githubusercontent.com/90202188/165096204-9b9d2582-7bbb-4f95-adcf-6281afe46e1d.png)

2022-04-25 13:26 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +                    Modalités pratiques
You can add this to the resources(translations).

2022-04-26 07:39 UTC, NourJammal commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +                    Modalités pratiques
Pour la v1 on a que le français 
On créera un ticket pour la creation des fichiers resources

2022-04-26 09:08 UTC, maxime-poulain approved these changes

2022-04-26 09:08 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +                    Modalités pratiques
Oki

2022-04-26 09:46 UTC, maxime-poulain requested changes

2022-04-26 09:46 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +                @Model.Training.TrainingStatus
```suggestion
                @Model.Training.TrainingPracticalModalities
```

2022-04-26 10:52 UTC, joe-coop commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
> +                    Modalités pratiques
I will add localization keys for translation https://smartjira.atlassian.net/browse/CFA-349

2022-04-26 13:22 UTC, merged