Add Trainer's details page
smartcoop/smart-cfa pull request #87
Opened 2022-04-26 13:25 UTC by CelineMarique

CFA > Showcase
Add trainer's details page

https://smartjira.atlassian.net/browse/CFA-272

Add sql script to create training detail view.
Add model in Domain project and update dbContext in Infrasturcture project.
Add viewModel and cshtml with proper layout in Web project.

2022-04-27 14:08 UTC, LievenPraet requested changes

2022-04-27 14:08 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +            return RedirectToPage("/404");
We could put the hard coded urls in an enum to avoid code duplication and to also have a clear overview of fixed urls

2022-04-27 14:08 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +            TempData["errorMessage"] = "There is no record for this request. Please try again.";
The text 'please try again' has not much use here
```suggestion
            TempData["errorMessage"] = "There is no record for this request.";
```

2022-04-27 14:08 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +            TempData["errorMessage"] = "This trainer does not exist! Please try again.";
No need for the exclamation mark or try again text
```suggestion
            TempData["errorMessage"] = "This trainer does not exist.";
```

2022-04-27 14:08 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +        foreach (var detail in trainerDetails.Where(detail => detail.SocialNetwork != null))
```suggestion
        foreach (var detail in trainerDetails.Where(detail => detail.SocialNetwork is not null))
```

2022-04-27 14:08 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetailsViewModel.cs
> +    public string SocialNetworkUrl { get; set; }
`SocialNetworkUrl` could be a property `Url` of the class `SocialNetwork`

2022-04-27 14:08 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetailsViewModel.cs
> +    public List<TrainingListViewModel> TrainerTrainings { get; set; } = new ();
No need for `Trainer` prefix

2022-04-27 15:17 UTC, maxime-poulain requested changes

2022-04-27 15:17 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/efpt.config.json
>  ﻿{
You are using an outdated config therefore generating from that doesnt fully work.

2022-04-27 15:17 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +                                                      List<Domain.Models.TrainingList> trainerTrainingList)
```suggestion
        List<Domain.Models.TrainingList> trainerTrainingList)
```

2022-04-27 15:17 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +        foreach (var trainerTraining in trainerTrainingsByIds)
It starts to be pretty long.
You can refactor also the mapping logic of the training viewmodels into an extension method and reuse it also in the training details page.
See::
https://gist.github.com/maxime-poulain/bf35a51a77c825a437ffcc52231e1bea

2022-04-27 15:17 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetailsViewModel.cs
> +    public string SocialNetworkUrl { get; set; }
@LievenPraet
It's the result of 
```sql
SELECT dbo.Trainer.Id
      ,dbo.Trainer.FirstName
      ,dbo.Trainer.LastName
      ,dbo.Trainer.Biography
      ,dbo.Trainer.Title
      ,dbo.TrainerPersonalNetwork.SocialNetwork
      ,dbo.TrainerPersonalNetwork.UrlToProfile
FROM dbo.Trainer
LEFT OUTER JOIN dbo.TrainerPersonalNetwork ON dbo.Trainer.Id = dbo.TrainerPersonalNetwork.TrainerId
```

2022-04-28 09:07 UTC, NourJammal commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainerDetails.sql
> +LEFT OUTER JOIN dbo.TrainerPersonalNetwork ON dbo.Trainer.Id = dbo.TrainerPersonalNetwork.TrainerId
A tickect will be created for this

2022-04-28 09:18 UTC, NourJammal commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainerDetails.sql
> +LEFT OUTER JOIN dbo.TrainerPersonalNetwork ON dbo.Trainer.Id = dbo.TrainerPersonalNetwork.TrainerId
in v2

2022-04-28 09:19 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainerDetails.sql
> +LEFT OUTER JOIN dbo.TrainerPersonalNetwork ON dbo.Trainer.Id = dbo.TrainerPersonalNetwork.TrainerId
👍

2022-04-28 13:46 UTC, maxime-poulain requested changes

2022-04-28 13:46 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainerDetails.cs
> +    public string ProfileImagePath { get; set; }
its the path from minio therefore it wont work using it as an <img>

2022-04-28 13:46 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
> +            <img src="@Model.Trainer.ProfileImagePath" class="trainer-image" alt="trainer-image" />
you will need to use some kind of default avatar i guess and create a ticket to integreate minio (i can explain a bit further in slack)

2022-04-28 13:46 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingDetails.cs
>  namespace Smart.FA.Catalog.Showcase.Domain.Models;
could add a break line between the namespace and the class ?

2022-04-28 13:46 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingList.cs
>  public partial class TrainingList
could add a break line between the namespace and the class ?

2022-04-29 12:18 UTC, maxime-poulain requested changes

2022-04-29 12:18 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetailsViewModel.cs
> +
break line

2022-04-29 12:18 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Smart.FA.Catalog.Showcase.Web.csproj
>    </ItemGroup>
the <ItemGroup>
 <Folder Include=Mapper" />
</ItemGroup>

can be removed

2022-04-29 13:32 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
> +            return RedirectToPage("/404");
But this needs to be merged first and then we will able to use that.

2022-04-29 13:38 UTC, LievenPraet commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingList.cs
>      public int TrainingId { get; set; }
```suggestion
    public int Id { get; set; }
```

2022-04-29 13:42 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingDetails.cs
> +    public string TrainingTitle { get; set; } = null!;
For the TrainingDetails (which is a sql view) Having just Id might be confusing:
Is it the Id of the trainingDetails ? Or is it the Id of the Training ?
What do you think @LievenPraet

2022-04-29 14:37 UTC, maxime-poulain commented on src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingDetails.cs
> +    public string TrainingTitle { get; set; } = null!;
I'd rather keep the Title not to confuse the TrainingTitle with the TrainerTitle.

2022-04-29 14:40 UTC, LievenPraet approved these changes

2022-04-29 14:43 UTC, LievenPraet approved these changes

2022-05-01 21:20 UTC, maxime-poulain approved these changes

2022-05-03 08:44 UTC, merged